# Batch 3 (2026-10-08): more species Pet Zone sells. Original text; conservative general-hobby ranges.
from care_data import A, P

MORE_ANIMALS = [
 A("black-neon-tetra","Black Neon Tetra","Hyphessobrycon herbertaxelrodi","fish","Characidae","Paraguay River basin, South America","1.75 in",(72,79),(5.5,7.5),15,"Peaceful","Schooling, keep 6+","Mid","Beginner","Omnivore: micro pellets, flakes, frozen foods","3-4 years",
  "A small, hardy tetra with a white-edged black body stripe. It is a different species from the common neon tetra, with its own look and slightly different water preferences, and it does well in a planted community tank.",
  ["Keep a group of six or more.","Not a neon tetra; do not rely on neon care notes for exact numbers.","Choose calm, small tankmates."],aka=["black neon tetras","black neon","hyphessobrycon herbertaxelrodi"]),
 A("green-neon-tetra","Green Neon Tetra","Paracheirodon simulans","fish","Characidae","Rio Negro and Orinoco basins, South America","1.25 in",(73,82),(5.5,7.0),10,"Peaceful, shy","Schooling, keep 8+","Mid","Intermediate","Micro pellets, crushed flakes, baby brine shrimp, small frozen foods","3-4 years",
  "A tiny cousin of the neon tetra with a green-blue stripe and a short red area at the tail. It is smaller and shyer than a neon and prefers softer, clean, stable water in a quiet planted tank.",
  ["Keep a group of eight or more.","Only pair with small, gentle tankmates.","Make changes to the water slowly."],aka=["green neon tetras","green neon","paracheirodon simulans"]),
 A("redtail-catfish","Redtail Catfish","Phractocephalus hemioliopterus","fish","Pimelodidae","Amazon and Orinoco basins, South America","36-48+ in",(72,82),(6.0,7.5),1000,"Predatory, will eat anything that fits","Solitary","Bottom to mid","Advanced","Carnivore: fish, shrimp, squid, large sinking pellets","15-20+ years",
  "Sold as a cute juvenile, the redtail catfish grows into a heavy, powerful fish about three to four feet long. It needs a tank measured in the high hundreds or thousands of gallons, which is why it is usually a fish for a public aquarium or a pond-sized setup.",
  ["Plan for a tank of 1,000 gallons or more before buying.","Do not keep with any fish small enough to swallow.","Use heavy equipment covers and strong filtration."],aka=["red tail catfish","redtail cat","red tailed catfish","red tail cat","phractocephalus hemioliopterus","phractocephalus hemiliopterus","redtail catfish phractocephalus hemioliopterus","redtail catfish phractocephalus"]),
 A("ghost-shrimp","Ghost Shrimp","Palaemonetes paludosus","invert","Palaemonidae","Southeastern United States","1.5-2 in",(68,82),(6.5,8.0),5,"Peaceful, but may eat tiny shrimp and fry","Groups of 3+","All levels","Beginner","Omnivore: algae wafers, sinking pellets, leftover food, biofilm","1-2 years",
  "A see-through freshwater shrimp that cleans up scraps and is fun to watch. It lives only about a year or two, and it is larger and more predatory than cherry shrimp, so do not count on baby shrimp surviving in the same tank.",
  ["Avoid copper-based medications.","Provide hiding spots for molting.","Do not mix with tiny shrimp you want to breed."],aka=["ghost shrimps","glass shrimp","palaemonetes","palaemonetes paludosus","ghost shrimp feeder"]),
 A("emerald-catfish","Emerald Catfish","Brochis splendens","fish","Callichthyidae","Upper Amazon basin, South America","3 in",(72,79),(6.0,7.5),30,"Peaceful","Groups of 5+","Bottom","Beginner","Omnivore: sinking pellets and wafers, frozen foods","8-10 years",
  "A shimmering green armored catfish that is taller and longer than most corydoras. Keep a group on soft sand or smooth gravel and feed foods that sink.",
  ["Keep five or more together.","Use smooth sand or fine gravel.","Needs a larger tank than small corydoras."],aka=["emerald green cory","emerald cory","emerald corydoras","corydoras splendens","short body catfish","brochis splendens","emerald green catfish"]),
 A("dwarf-neon-rainbowfish","Dwarf Neon Rainbowfish","Melanotaenia praecox","fish","Melanotaeniidae","Northern New Guinea","3 in",(74,80),(6.5,7.8),20,"Peaceful, active","Schooling, keep 6+","Upper to mid","Beginner","Omnivore: micro pellets, flakes, frozen foods","4-5 years",
  "A small, bright rainbowfish with a blue body and red fins. It is a good fit for medium community tanks, needs a group and open swimming space, and does best in clean, moderately hard water.",
  ["Keep a group of six or more.","Use a tight lid; rainbowfish jump.","Feed small portions, twice a day."],aka=["dwarf neon rainbow","neon dwarf rainbowfish","praecox rainbowfish","melanotaenia praecox"]),
 A("blue-acara","Blue Acara","Andinoacara pulcher","fish","Cichlidae","Panama, Colombia and Venezuela","6-8 in",(72,82),(6.5,7.8),55,"Semi-aggressive, territorial when breeding","Pair or solitary","Bottom to mid","Intermediate","Omnivore: cichlid pellets, frozen foods, vegetables","8-10 years",
  "A hardy, medium-sized cichlid with blue-green markings. It is calmer than most large cichlids but will eat small fish and defend a territory when breeding.",
  ["Do not keep with small fish like neons.","Provide caves and open swimming space.","Use a sturdy lid and strong filtration."],aka=["blue acara cichlid","andinoacara pulcher","aequidens pulcher","electric blue acara"]),
 A("keyhole-cichlid","Keyhole Cichlid","Cleithracara maronii","fish","Cichlidae","The Guianas, South America","4 in",(72,80),(6.0,7.5),30,"Peaceful, shy","Pairs or small groups","Bottom to mid","Intermediate","Omnivore: small pellets, frozen foods, live foods","8-10 years",
  "A calm, shy cichlid named for the keyhole-shaped dark mark on its side. It does best in a quiet tank with plants, caves and gentle tankmates.",
  ["Use calm tankmates; boisterous fish stress it.","Provide caves and plants.","Keep water clean and stable."],aka=["keyhole cichlids","cleithracara maronii","keyhole cichlid cleithracara maronii"]),
 A("sparkling-gourami","Sparkling Gourami","Trichopsis pumila","fish","Osphronemidae","Southeast Asia","1.5 in",(72,82),(6.0,7.5),10,"Peaceful, shy","Pairs or small groups","Upper to mid","Intermediate","Carnivore: micro pellets, baby brine shrimp, small frozen foods","3-4 years",
  "A tiny labyrinth fish with iridescent dots and the ability to make soft croaking sounds. It needs a calm, planted tank with floating plants and very gentle tankmates.",
  ["Leave an air gap under the lid.","Use floating plants for cover.","Feed tiny live or frozen foods."],aka=["sparkling gouramis","croaking gourami","trichopsis pumila"]),
 A("pearl-danio","Pearl Danio","Danio albolineatus","fish","Danionidae","Thailand, Myanmar and Sumatra","2.5 in",(68,79),(6.0,8.0),20,"Peaceful, very active","Schooling, keep 6+","Upper to mid","Beginner","Omnivore: flakes, micro pellets, frozen foods","3-5 years",
  "A fast, hardy schooling danio with a pearly sheen and a hint of pink or blue. It needs a long tank with open water and a secure lid.",
  ["Keep a group of six or more.","Use a tight lid; danios jump.","Choose a tank that is at least two feet long."],aka=["pearl danios","danio albolineatus","pearly danio"]),
 A("red-eye-tetra","Red Eye Tetra","Moenkhausia sanctaefilomenae","fish","Characidae","Paraguay River basin, South America","2.5 in",(72,80),(6.0,7.5),20,"Active, mostly peaceful, may nip long fins","Schooling, keep 6+","Mid to upper","Beginner","Omnivore: flakes, micro pellets, frozen foods","4-5 years",
  "A silver tetra with a red ring above the eye. Hardy and active, it likes to be in a group and may nibble the fins of long-finned fish.",
  ["Keep a group of six or more.","Avoid long-finned tankmates.","Tough plants work best; it can nibble soft ones."],aka=["red eye tetras","redeye tetra","moenkhausia sanctaefilomenae","red eyed tetra"]),
 A("checker-barb","Checker Barb","Oliotius oligolepis","fish","Cyprinidae","Sumatra and nearby islands, Indonesia","2 in",(68,77),(6.0,7.5),20,"Peaceful, active","Schooling, keep 6+","Mid to lower","Beginner","Omnivore: flakes, micro pellets, frozen foods","4-5 years",
  "A small, peaceful barb with a checkered scale pattern and orange-tinged fins on the males. It is hardy, likes cooler water than many tropical fish, and is a calm pick for community tanks.",
  ["Keep a group of six or more.","Tolerates cooler tropical temperatures.","Use a lid; barbs can jump."],aka=["checkered barb","checker barbs","oliotius oligolepis","puntius oligolepis","island barb"]),
 A("columbian-tetra","Columbian Tetra","Hyphessobrycon columbianus","fish","Characidae","Colombia, South America","2.5 in",(72,80),(6.0,7.5),30,"Active, may nip long fins","Schooling, keep 6+","Mid","Beginner","Omnivore: flakes, micro pellets, frozen foods","4-5 years",
  "A sturdy tetra with a blue-violet sheen and a reddish tail. It is more active than neon-type tetras and can nibble long fins, so pair it with fast, similar-sized fish.",
  ["Keep a group of six or more.","Avoid bettas and other long-finned fish.","Give it open swimming room."],aka=["colombian tetra","columbian tetras","hyphessobrycon columbianus"]),
 A("rosy-tetra","Rosy Tetra","Hyphessobrycon bentosi","fish","Characidae","Amazon basin, South America","2 in",(74,82),(5.5,7.5),20,"Peaceful","Schooling, keep 6+","Mid","Beginner","Omnivore: flakes, micro pellets, frozen foods","3-4 years",
  "A peaceful tetra with a rosy body and a black-and-white edged dorsal fin on males. Good for a planted community tank; the long-finned variety is more delicate.",
  ["Keep a group of six or more.","Choose calm tankmates.","Keep water clean and stable."],aka=["rosy tetras","hyphessobrycon bentosi","hyphessobrycon rosaceus","rosy tetra long fin"]),
 A("ruby-tetra","Ruby Tetra","Axelrodia riesei","fish","Characidae","Upper Meta River, Colombia","1 in",(75,82),(5.5,7.0),10,"Peaceful, shy","Schooling, keep 8+","Lower to mid","Intermediate","Micro pellets, crushed flakes, baby brine shrimp","2-3 years",
  "A tiny, shy tetra with a red-orange shimmer. It is best in a calm planted tank with soft, clean water and only very small, gentle tankmates.",
  ["Keep eight or more.","Do not mix with boisterous fish.","Add only to a mature tank."],aka=["ruby tetras","axelrodia riesei","ruby red tetra"]),
 A("gold-tetra","Gold Tetra","Hemigrammus rodwayi","fish","Characidae","Guyana and nearby northern South America","2 in",(72,82),(6.0,7.5),20,"Peaceful, active","Schooling, keep 6+","Mid","Beginner","Omnivore: flakes, micro pellets, frozen foods","4-5 years",
  "A hardy tetra with gold-glinting scales. It is calm and a good choice for beginners with a community tank.",
  ["Keep a group of six or more.","Tolerates a range of water.","Use gentle filtration."],aka=["gold tetras","golden tetra","hemigrammus rodwayi","brass tetra"]),
 A("glowlight-danio","Glowlight Danio","Danio choprae","fish","Danionidae","Myanmar","1.5 in",(72,79),(6.5,7.5),10,"Peaceful, active","Schooling, keep 6+","Upper to mid","Beginner","Omnivore: micro pellets, flakes, small frozen foods","3-4 years",
  "A small, peaceful danio with a glowing orange stripe. It suits a small community tank and needs a lid, since danios jump.",
  ["Keep a group of six or more.","Use a tight lid.","Feed small foods."],aka=["glowlight danios","danio choprae","danio choprai","glow light danio"]),
 A("five-banded-barb","Five-Banded Barb","Desmopuntius pentazona","fish","Cyprinidae","Malay Peninsula, Sumatra and Borneo","1.75 in",(75,82),(5.0,7.0),20,"Peaceful, shy","Schooling, keep 8+","Mid","Intermediate","Omnivore: micro pellets, flakes, frozen foods","4-5 years",
  "A small barb with bold dark bands. It is shy, likes soft, slightly acidic water and a planted tank with calm tankmates; often kept in a larger group to look its best.",
  ["Keep eight or more.","Do not mix with fast, boisterous fish.","Plants and wood help it feel secure."],aka=["five banded barb","five-banded barbs","5 banded barb","desmopuntius pentazona","puntius pentazona","hexazona barb"]),
 A("glass-catfish","Glass Catfish","Kryptopterus vitreolus","fish","Siluridae","Thailand and nearby Southeast Asia","3 in",(73,79),(6.5,7.5),30,"Peaceful, timid","Schooling, keep 6+","Mid","Intermediate","Small live, frozen or sinking foods; some fish accept micro pellets","5-8 years",
  "A transparent catfish that swims in mid-water and needs a group. It is shy and sensitive to poor water, so do not mix it with bullies or fast feeders.",
  ["Keep a group of six or more.","Avoid strong flow and boisterous tankmates.","Do not dye-treat or paint-dye fish; buy natural fish."],aka=["glass catfishes","ghost catfish","kryptopterus vitreolus","kryptopterus minor","kryptopterus bicirrhis"]),
 A("upside-down-catfish","Upside-Down Catfish","Synodontis nigriventris","fish","Mochokidae","Congo basin, Africa","3-4 in",(73,79),(6.0,7.5),30,"Peaceful","Groups of 3+","All levels","Beginner","Omnivore: sinking pellets, frozen foods, algae","8-10 years",
  "A small synodontis that often swims upside down at the surface or under plants and wood. It is peaceful, nocturnal and happiest with caves and a group.",
  ["Provide caves and wood.","Keep at least three if the tank allows.","Do not mix with tiny shrimp."],aka=["upside down catfish","upside-down cats","synodontis nigriventris","upside down synodontis","upside down cat"]),
 A("bumblebee-catfish","Bumblebee Catfish","Microglanis iheringi","fish","Pseudopimelodidae","Northern South America","3 in",(72,79),(6.0,7.5),20,"Predatory toward tiny fish and shrimp","Pairs or small groups","Bottom","Intermediate","Carnivore: frozen foods, live foods, sinking pellets","8-12 years",
  "A small, boldly banded catfish that hides by day. It will eat fish and shrimp that fit in its mouth, so keep it with fish bigger than about an inch and a half.",
  ["Provide caves and cover.","Do not keep with neons or small shrimp.","Feed sinking foods in the evening."],aka=["bumblebee catfish","bumble bee catfish","microglanis iheringi","bumble bee cat"]),
 A("festivum-cichlid","Festivum Cichlid","Mesonauta festivus","fish","Cichlidae","Amazon and Orinoco basins, South America","6 in",(75,82),(5.5,7.5),55,"Peaceful to semi-aggressive","Pairs or small groups","Mid","Intermediate","Omnivore: cichlid pellets, flakes, frozen foods","8-10 years",
  "A tall, flat-bodied cichlid with a dark flank stripe. It is calmer than many cichlids but can be territorial when breeding and may eat very small fish.",
  ["Provide height, caves and wood.","Do not keep with tiny tetras.","Use a larger tank for a group."],aka=["festivum cichlids","festivum","flag cichlid","mesonauta festivus","festivum cichlid mesonauta festivus"]),
 A("green-terror","Green Terror","Andinoacara rivulatus","fish","Cichlidae","Ecuador and Peru, South America","8-12 in",(68,79),(6.5,7.5),75,"Aggressive, territorial","Pair or solitary","Bottom to mid","Intermediate","Omnivore: cichlid pellets, frozen foods, vegetables","8-10 years",
  "A bold, blue-green cichlid with a bright face. Males grow big and aggressive and are best in a large tank with sturdy tankmates of similar size.",
  ["Plan for a large tank for an adult.","Provide caves and broken sight lines.","Do not keep with small fish."],aka=["green terror cichlid","gold saum green terror","andinoacara rivulatus","aequidens rivulatus","gold saum","green terror cichlids"]),
 A("sailfin-pleco","Sailfin Pleco","Pterygoplichthys gibbiceps","fish","Loricariidae","Amazon basin, South America","16-20 in",(72,82),(6.5,7.5),125,"Peaceful, may become territorial with other plecos","Solitary","Bottom","Intermediate","Herbivore: algae wafers, vegetables, driftwood, some protein","10-15 years",
  "A spotted pleco with a tall sail-like dorsal fin. It grows far larger than the juveniles sold, needs a very large tank and produces a lot of waste. Never release it into local waters.",
  ["Plan on a large tank for an adult.","Provide driftwood and hiding places.","Do not release plecos outdoors."],aka=["leopard pleco","sailfin plecostomus","pterygoplichthys gibbiceps","leopard sailfin pleco","gibbiceps pleco","sailfin plecos"]),
 A("rubber-lip-pleco","Rubber Lip Pleco","Chaetostoma milesi","fish","Loricariidae","Colombia, South America","6-7 in",(68,78),(6.5,7.5),40,"Peaceful","Solitary or small groups","Bottom","Intermediate","Herbivore: algae wafers, blanched vegetables, biofilm","8-10 years",
  "A mid-sized, grey-spotted pleco from flowing water. It likes cooler tropical temperatures, strong oxygen and driftwood to rasp on.",
  ["Use good filtration and oxygenation.","Provide driftwood and rock.","Feed vegetables as well as wafers."],aka=["rubber lipped pleco","rubberlip pleco","chaetostoma milesi","rubber lip plecostomus","rubbernose pleco"]),
 A("kissing-gourami","Kissing Gourami","Helostoma temminckii","fish","Helostomatidae","Southeast Asia","6-12 in",(72,82),(6.5,8.0),55,"Peaceful to semi-aggressive","Solitary or pairs","Mid to upper","Intermediate","Omnivore: flakes, pellets, algae, vegetables","8-10 years",
  "A large gourami known for its lip-to-lip pushing, which is usually a contest, not affection. It grows bigger than most store fish suggest and eats a lot of plant matter.",
  ["Plan for a large tank.","Expect plants to be nibbled.","Leave an air gap under the lid."],aka=["kissing gouramis","pink kissing gourami","green kissing gourami","helostoma temminckii","kisser fish"]),
 A("chocolate-gourami","Chocolate Gourami","Sphaerichthys osphromenoides","fish","Osphronemidae","Malay Peninsula, Sumatra and Borneo","2.5 in",(75,82),(4.5,6.5),20,"Peaceful, shy","Pairs or small groups","Mid","Advanced","Small live and frozen foods; many refuse dry food","3-5 years",
  "A delicate, shy gourami that wants soft, acidic, spotless water and calm tankmates. It is not a beginner fish and is easily stressed by moves and poor water.",
  ["Use only a mature, stable tank.","Offer small live or frozen foods.","Do not mix with active fish."],aka=["chocolate gouramis","sphaerichthys osphromenoides","chocolate gourami sphaerichthys osphromenoides"]),
]

MORE_PLANTS = [
 P("dwarf-sagittaria","Dwarf Sagittaria","Sagittaria subulata","Alismataceae","Eastern Americas","2-10 in","Low to medium","Optional","Foreground to midground","Medium",(65,82),(6.0,7.5),"Beginner","Runners",
  "A grass-like plant that sends out runners and carpets the front of a tank. It grows taller in strong light, so trim to keep it low.",
  ["Plant the crown at substrate level, not buried.","Root tabs help it spread.","Trim tall leaves to keep it as a carpet."],aka=["sagittaria subulata","dwarf sag","dwarf sagittaria subulata","dwarf sagittaria sagittaria subulata"]),
 P("water-sprite","Water Sprite","Ceratopteris thalictroides","Pteridaceae","Tropical regions worldwide","6-20 in","Low to high","Not needed","Planted or floating","Fast",(68,82),(6.0,7.5),"Beginner","Plantlets and cuttings",
  "A fast, feathery fern that soaks up nutrients quickly and gives fry and shy fish cover. It can be planted in the substrate or left floating.",
  ["Remove or replant the baby plantlets that form on old leaves.","Floating plants soften the light for fish that like shade.","Trim often to keep it from shading other plants."],aka=["water sprite plant","ceratopteris thalictroides","indian fern","oriental water sprite"]),
 P("cryptocoryne-balansae","Cryptocoryne Balansae","Cryptocoryne balansae","Araceae","Thailand and Vietnam","8-20 in","Low to medium","Not needed","Midground to background","Slow",(72,82),(6.0,8.0),"Intermediate","Runners",
  "A cryptocoryne with long, crinkled strap-like leaves. It may melt after planting, then regrow; leave it alone.",
  ["Do not move it once planted.","Use root tabs.","Expect melt after changes."],aka=["crypt balansae","cryptocoryne balansae","cryptocoryne balansae gigantea","crypt balansae plant"]),
 P("rotala-wallichii","Rotala Wallichii","Rotala wallichii","Lythraceae","Southeast Asia","6-12 in","Medium to high","Recommended","Midground to background","Moderate",(72,82),(5.0,7.0),"Advanced","Cuttings",
  "A fine-leaved stem with a feathery look. It does best in soft water with CO2 and steady nutrients.",
  ["Provide good light and CO2.","Trim tops and replant.","Keep water soft."],aka=["rotala wallichii","rotala wallichi","rotala wallichii plant"]),
 P("ludwigia-arcuata","Ludwigia Arcuata","Ludwigia arcuata","Onagraceae","Southeastern United States","8-16 in","Medium to high","Optional","Midground to background","Moderate",(70,82),(6.0,7.5),"Intermediate","Cuttings",
  "A needle-leaf stem plant with orange to red tones under bright light. It is easy to trim and replant.",
  ["Use stronger light for color.","Trim and replant tops.","Keep it fed."],aka=["needle leaf ludwigia","ludwigia arcuata","ludwigia arcuata needle leaf"]),
 P("bacopa-monnieri","Bacopa Monnieri","Bacopa monnieri","Plantaginaceae","Tropical regions worldwide","8-20 in","Low to medium","Not needed","Midground to background","Moderate",(68,82),(6.0,7.5),"Beginner","Cuttings",
  "A hardy stem plant with rounded leaves, sometimes called water hyssop. It adapts well and can grow above the water.",
  ["Plant stems 1 inch apart.","Trim tops often.","Works in low-tech tanks."],aka=["bacopa monnieri","water hyssop","bacopa monnieri plant"]),
 P("subwassertang","Subwassertang","Lomariopsis cf. lineata","Lomariopsidaceae","Southeast Asia","2-8 in","Low to medium","Not needed","Anywhere, tied to hardscape","Slow",(60,79),(6.0,7.5),"Beginner","Division",
  "A feathery, moss-like fern. It is easy, drapes over wood and rock, and gives shrimp and fry cover.",
  ["Tie to wood with thread.","Trim to shape.","Keep debris off it."],aka=["freshwater seaweed","freshwater sea weed","lomariopsis lineata","lomariopsis cf lineata","sub tang"]),
]

ALIAS_INTO = {}
