# Batch 2: species Pet Zone sells that are not in care_data.py. Original text; general hobby ranges, conservative.
from care_data import A, P

MORE_ANIMALS = [
 A("african-dwarf-frog","African Dwarf Frog","Hymenochirus boettgeri","amphibian","Pipidae","Central Africa","2 in",(72,82),(6.5,7.8),5,"Peaceful, poor eyesight","Groups of 2+","All levels","Beginner","Carnivore: frozen bloodworms, brine shrimp, sinking frog pellets","5 years",
  "A small, fully aquatic frog that needs a lid with an air gap because it surfaces to breathe. Its eyesight is poor, so it often loses out on food to fast tankmates.",
  ["Use a lid with a small air gap and no open edges.","Feed sinking foods or target-feed with a pipette.","Do not mix with large or fast fish; keep calm tankmates."],aka=["adf","african dwarf frogs","african dwarf frog blonde","dwarf zaire platinum african dwarf frog","dwarf aquatic frog","zaire dwarf frog"]),
 A("fire-belly-newt","Fire Belly Newt","Cynops orientalis","amphibian","Salamandridae","Eastern China","3.5 in",(60,72),(6.5,7.5),10,"Peaceful","Groups of 2-3","Water and land","Intermediate","Carnivore: frozen bloodworms, blackworms, sinking carnivore pellets","10-15 years",
  "A hardy, mostly aquatic newt with a bright orange belly that likes cool water. Provide a land area and a very secure lid, and wash your hands before and after handling anything in the tank.",
  ["Keep it cool; avoid temperatures above the low 70s.","Provide a land area or floating perch and a tight lid.","Wash hands before and after touching the tank; its skin has mild toxins."],aka=["fire belly newts","chinese fire belly newt","cynops","firebelly newt","fire-bellied newt"]),
 A("paddletail-newt","Paddletail Newt","Pachytriton labiatus","amphibian","Salamandridae","Southern China","6 in",(55,68),(6.5,7.5),20,"Peaceful, shy","Small groups","Water and bottom","Intermediate","Carnivore: frozen bloodworms, blackworms, earthworms, sinking pellets","15-20 years",
  "A large, mostly aquatic newt that needs cool, well-oxygenated water and plenty of hiding spots. It struggles in warm tanks, so a chiller or a cool room matters.",
  ["Keep it cool, ideally under 70°F.","Provide caves and hiding spots.","Use a tight lid and strong filtration."],aka=["paddletail newts","paddle tail newt","pachytriton","paddletail"]),
 A("spanish-ribbed-newt","Spanish Ribbed Newt","Pleurodeles waltl","amphibian","Salamandridae","Spain, Portugal and Morocco","8-10 in",(60,74),(6.5,8.0),30,"Peaceful but eats small tankmates","Solitary or pairs","Water and bottom","Intermediate","Carnivore: frozen bloodworms, earthworms, sinking pellets","15-20 years",
  "A large, hardy, mostly aquatic newt that is easy to feed. When threatened it can push its ribs through its skin, so handle as little as possible and keep it away from small fish and shrimp.",
  ["Keep it cool; avoid warm rooms.","Do not keep with small fish or shrimp.","Use a tight lid and some land or a floating perch."],aka=["spanish ribbed newts","leucistic spanish ribbed newt","juvenile spanish ribbed newt","pleurodeles waltl","ribbed newt"]),

 A("shovelnose-catfish","Shovelnose Catfish","Pseudoplatystoma and Sorubim species","fish","Pimelodidae","South America","24-48+ in",(72,82),(6.0,7.5),500,"Predatory","Solitary","Bottom to mid","Advanced","Carnivore: frozen fish, shrimp, pellets","15+ years",
  "Tiger shovelnose and related catfish are sold small but grow into very large predators, often over three feet long. They eat any fish that fits in their mouths and need a huge tank, many hundreds of gallons for a tiger.",
  ["Needs a very large tank; juveniles outgrow home tanks fast.","Do not keep with smaller fish."],aka=["tiger shovelnose catfish","tiger shovel nose catfish","tiger shovelnose","redtail tiger shovelnose hybrid catfish","lima shovel nosed catfish","sorubim lima","spotted hybrid tiger shovel nose catfish"]), # ---- Tetras ----
 A("serpae-tetra","Serpae Tetra","Hyphessobrycon eques","fish","Characidae","Paraguay and Amazon basins, South America","1.75 in",(72,82),(5.5,7.5),20,"Semi-aggressive, fin nipper","Schooling, keep 6+","Mid","Beginner","Omnivore: flakes, pellets, frozen foods","4-5 years",
  "A bold red tetra that does best in a group of six or more, which spreads out its fin nipping. Keep it away from long-finned tankmates.",
  ["Always keep a group; singles get nippy.","Pick fast, short-finned tankmates."],aka=["serpae"]),
 A("bleeding-heart-tetra","Bleeding Heart Tetra","Hyphessobrycon erythrostigma","fish","Characidae","Amazon basin, South America","3 in",(75,82),(5.5,7.5),30,"Peaceful","Schooling, keep 6+","Mid","Intermediate","Omnivore: flakes, pellets, frozen foods","4-6 years",
  "A deep-bodied tetra with a red spot behind the gill. Males grow tall, flowing dorsal fins. Likes warm, clean water and a planted tank.",
  ["Give it a tank 30 gallons or larger.","Keep a group of six or more."],aka=["bleeding heart"]),
 A("buenos-aires-tetra","Buenos Aires Tetra","Hyphessobrycon anisitsi","fish","Characidae","Parana and Paraguay basins, South America","2.5 in",(68,82),(6.0,8.0),20,"Active, may nip and eat plants","Schooling, keep 6+","Mid","Beginner","Omnivore: flakes, pellets, plant matter","4-5 years",
  "A hardy, fast tetra that tolerates cooler water. It nibbles soft plants, so tough plants like anubias and java fern work best.",
  ["Offer vegetable-based foods to reduce plant nibbling.","Needs swimming room."],aka=["buenos aires tetras"]),
 A("x-ray-tetra","X-Ray Tetra","Pristella maxillaris","fish","Characidae","Guianas and Amazon basin, South America","2 in",(72,82),(6.0,7.5),15,"Peaceful","Schooling, keep 6+","Mid","Beginner","Omnivore: flakes, micro pellets","4-5 years",
  "A hardy, translucent tetra whose skeleton shows through its skin. A forgiving first fish for a community tank.",
  ["Keep a group of six or more.","Tolerates a range of water conditions."],aka=["pristella tetra","x ray tetra","x-ray pristella tetra"]),
 A("flame-tetra","Flame Tetra","Hyphessobrycon flammeus","fish","Characidae","Rio de Janeiro region, Brazil","1.75 in",(68,82),(5.5,7.5),15,"Peaceful","Schooling, keep 6+","Mid","Beginner","Omnivore: flakes, micro pellets","3-4 years",
  "A small, hardy tetra with a red rear half. Tolerates cooler water than many tetras.",
  ["Keep a group of six or more.","Good with other small, peaceful fish."],aka=["von rio tetra","von rio","flame tetra von rio"]),
 A("diamond-tetra","Diamond Tetra","Moenkhausia pittieri","fish","Characidae","Lake Valencia, Venezuela","2.5 in",(72,82),(6.0,8.0),20,"Peaceful","Schooling, keep 6+","Mid","Beginner","Omnivore: flakes, pellets, frozen foods","4-5 years",
  "A sparkling, silvery tetra with glittering scales. Males develop longer fins as they mature.",
  ["Keep a group of six or more.","Look best under moderate lighting with dark substrate."],aka=["diamond tetras"]),
 A("penguin-tetra","Penguin Tetra","Thayeria boehlkei","fish","Characidae","Araguaia basin, Brazil","3 in",(72,82),(6.0,7.5),20,"Peaceful","Schooling, keep 6+","Upper to mid","Beginner","Omnivore: flakes, micro pellets","4-5 years",
  "A slim tetra that swims at a slight head-up angle, with a bold black stripe. Likes open swimming room.",
  ["Keep a group of six or more.","Use a tight-fitting lid."],aka=["penguin tetras"]),
 A("black-phantom-tetra","Black Phantom Tetra","Hyphessobrycon megalopterus","fish","Characidae","Paraguay basin, South America","1.75 in",(72,82),(6.0,7.5),15,"Peaceful","Schooling, keep 6+","Mid","Beginner","Omnivore: flakes, micro pellets","3-4 years",
  "A small, calm tetra with a black body and a tall dorsal fin on males. Easy to keep with other peaceful community fish.",
  ["Keep a group of six or more.","Stable, clean water brings out color."],aka=["black phantom"]),
 A("red-phantom-tetra","Red Phantom Tetra","Hyphessobrycon sweglesi","fish","Characidae","Colombia and Venezuela, South America","1.75 in",(72,82),(5.5,7.5),15,"Peaceful","Schooling, keep 6+","Mid","Beginner","Omnivore: flakes, micro pellets","3-4 years",
  "A small tetra with a red body and a dark spot behind the gill. A peaceful, easy community fish.",
  ["Keep a group of six or more.","Floating plants help them feel secure."],aka=["red phantom"]),
 A("bloodfin-tetra","Bloodfin Tetra","Aphyocharax anisitsi","fish","Characidae","Parana basin, Argentina","2 in",(64,82),(6.0,8.0),20,"Active, peaceful","Schooling, keep 6+","Mid to upper","Beginner","Omnivore: flakes, micro pellets","4-5 years",
  "A hardy silver tetra with red fins that tolerates a wide temperature range. Active and quick, so give it swimming space.",
  ["Keep a group of six or more.","Use a lid; they jump."],aka=["bloodfin"]),
 A("glofish-tetra","GloFish Tetra","Gymnocorymbus ternetzi (selectively bred, fluorescent)","fish","Characidae","Captive-bred","2.5 in",(70,80),(6.0,7.5),20,"Peaceful, may nip long fins","Schooling, keep 6+","Mid","Beginner","Omnivore: flakes, pellets","3-5 years",
  "A brightly fluorescent, captive-bred variety of the black skirt tetra. Care is the same as for black skirt tetras; the color comes from selective breeding.",
  ["Keep a group of six or more.","Blue or black lighting makes the glow stand out."],aka=["glofish","glo fish","glofish tetras"]),
 A("emperor-tetra","Emperor Tetra","Nematobrycon palmeri","fish","Characidae","Colombia, South America","2.5 in",(73,81),(6.0,7.5),20,"Peaceful","Small groups, 4+","Mid","Beginner","Omnivore: flakes, pellets, frozen foods","4-5 years",
  "A calm tetra with a violet sheen and a blue eye. Males are larger and have longer center tail rays.",
  ["Keep a small group with a few more females than males.","Gentle tankmates only."],aka=["emperor tetras","black emperor tetra"]),
 A("blue-tetra","Blue Tetra","Boehlkea fredcochui","fish","Characidae","Upper Amazon basin, South America","2 in",(72,82),(6.0,7.5),20,"Peaceful","Schooling, keep 6+","Mid","Beginner","Omnivore: flakes, micro pellets","3-5 years",
  "A silvery-blue schooling tetra with a calm temperament. Looks best in a group in a planted tank.",
  ["Keep a group of six or more."],aka=["columbian tetra","colombian tetra","cochus blue tetra"]),
 A("bucktooth-tetra","Bucktooth Tetra","Exodon paradoxus","fish","Characidae","Guianas and Amazon basin, South America","4 in",(75,82),(5.5,7.5),40,"Semi-aggressive, fin nipper","Schooling, keep 6+","Mid","Intermediate","Carnivore leaning omnivore: pellets, frozen foods","5-6 years",
  "A bold, active tetra that nips the fins and scales of tankmates. Best with fast, similar-sized fish in a roomy tank.",
  ["Keep a group of six or more.","Avoid slow or long-finned tankmates."],aka=["exodon","bucktooth tetras"]),
 A("silver-tip-tetra","Silver Tip Tetra","Hasemania nana","fish","Characidae","Sao Francisco basin, Brazil","2 in",(68,82),(6.0,7.5),20,"Peaceful, can nip","Schooling, keep 6+","Mid","Beginner","Omnivore: flakes, micro pellets","4-5 years",
  "A hardy, active tetra with white-tipped fins. A group keeps it busy and calm.",
  ["Keep a group of six or more."],aka=["silvertip tetra","silver tip tetras"]),
 A("hatchetfish","Hatchetfish","Gasteropelecus and Carnegiella species","fish","Gasteropelecidae","Amazon basin, South America","2 in",(73,82),(5.5,7.0),20,"Peaceful","Schooling, keep 6+","Top","Intermediate","Surface feeder: flies, small floating foods","3-5 years",
  "Surface-dwelling fish with deep keel-shaped bellies that can jump out of the water. A tight lid and floating plants are essential.",
  ["Use a very secure lid.","Feed small floating foods and live or frozen insects.","Keep a group of six or more."],aka=["silver hatchetfish","marble hatchetfish","pygmy hatchetfish"]),
 # ---- Rasboras, danios, barbs ----
 A("clown-rasbora","Clown Rasbora","Rasbora kalochroma","fish","Danionidae","Southeast Asia","4 in",(72,80),(5.5,7.5),30,"Peaceful","Schooling, keep 6+","Mid","Intermediate","Omnivore: flakes, pellets, frozen foods","4-6 years",
  "A larger rasbora with a red-orange body and bold black spots. Needs a roomy, planted tank and soft, clean water.",
  ["Keep a group of six or more.","Do regular water changes."],aka=["clown rasboras"]),
 A("strawberry-rasbora","Strawberry Rasbora","Boraras naevus","fish","Danionidae","Borneo","0.8 in",(72,80),(5.0,7.0),5,"Peaceful","Schooling, keep 8+","Mid","Intermediate","Micro pellets, baby brine shrimp, crushed flakes","3-4 years",
  "A tiny, blush-red nano fish best kept with other small, peaceful species and shrimp. Prefers soft, clean, planted setups.",
  ["Feed very small foods.","Keep a group of eight or more."],aka=["strawberry rasboras","boraras naevus"]),
 A("pygmy-rasbora","Pygmy Rasbora","Boraras maculatus","fish","Danionidae","Malay Peninsula and Sumatra","0.8 in",(72,82),(5.0,7.0),5,"Peaceful","Schooling, keep 8+","Mid","Intermediate","Micro pellets, baby brine shrimp","3-4 years",
  "A tiny red-orange rasbora with a bold spot pattern, ideal for nano planted tanks.",
  ["Keep a group of eight or more.","Pair with other tiny peaceful fish and shrimp."],aka=["dwarf rasbora","dwarf rasbora boraras maculatus","spotted rasbora","dwarf spotted rasbora"]),
 A("espei-rasbora","Espei Rasbora","Trigonostigma espei","fish","Danionidae","Southeast Asia","1.5 in",(72,82),(6.0,7.5),10,"Peaceful","Schooling, keep 6+","Mid","Beginner","Omnivore: flakes, micro pellets","3-5 years",
  "A small orange rasbora with a dark wedge, closely related to the harlequin. Calm and easy in a planted community tank.",
  ["Keep a group of six or more."],aka=["lambchop rasbora","lambchop"]),
 A("emerald-dwarf-rasbora","Emerald Dwarf Rasbora","Danionella erythromicron","fish","Danionidae","Myanmar","0.8 in",(72,80),(6.0,7.5),10,"Peaceful, shy","Schooling, keep 8+","Mid","Intermediate","Micro pellets, baby brine shrimp, small frozen foods","3-4 years",
  "A tiny rasbora with a blue-green sheen and orange fins. Needs peaceful tankmates and small foods.",
  ["Feed tiny foods they can swallow.","Keep a group of eight or more."],aka=["emerald rasbora","emerald eye rasbora","celestichthys erythromicron"]),
 A("giant-danio","Giant Danio","Devario aequipinnatus","fish","Danionidae","South Asia","4 in",(65,80),(6.0,8.0),30,"Active, peaceful","Schooling, keep 6+","Upper to mid","Beginner","Omnivore: flakes, pellets, frozen foods","4-5 years",
  "A fast, hardy danio that needs a long tank and a tight lid. Great for active community tanks with similarly sized fish.",
  ["Use a tight lid; they jump.","Give it a long tank for swimming."],aka=["giant danios"]),
 A("leopard-danio","Leopard Danio","Danio rerio (spotted variety)","fish","Danionidae","Captive-bred variety","2.5 in",(65,78),(6.5,7.5),15,"Active, peaceful","Schooling, keep 6+","Upper","Beginner","Omnivore: flakes, pellets","3-5 years",
  "A spotted variety of the zebra danio. Hardy, active and easy, and tolerates cooler water.",
  ["Keep a group of six or more.","Use a lid."],aka=["longfin leopard danio","longfin zebra danio","blue zebra danio","glolite danio"]),
 A("rosy-barb","Rosy Barb","Pethia conchonius","fish","Cyprinidae","Northern India","3 in",(64,77),(6.0,8.0),20,"Active, peaceful","Schooling, keep 6+","Mid","Beginner","Omnivore: flakes, pellets, vegetables","4-6 years",
  "A hardy barb that tolerates cooler tanks. Males flush rosy red when mature. Keep a group to calm any chasing.",
  ["Keep a group of six or more.","Do not pair with slow, long-finned fish."],aka=["rosy barbs","longfin rosy barb","long fin rosy barb"]),
 A("odessa-barb","Odessa Barb","Pethia padamya","fish","Cyprinidae","Myanmar","2.5 in",(65,77),(6.5,7.5),20,"Active, peaceful","Schooling, keep 6+","Mid","Beginner","Omnivore: flakes, pellets","3-5 years",
  "A hardy barb whose males show a bright red band along the body. Active and easy to keep.",
  ["Keep a group of six or more."],aka=["odessa barbs"]),
 A("ruby-barb","Ruby Barb","Pethia nigrofasciata","fish","Cyprinidae","Sri Lanka","2.5 in",(72,80),(6.0,7.0),20,"Active, peaceful","Schooling, keep 6+","Mid","Beginner","Omnivore: flakes, pellets, vegetables","4-5 years",
  "A peaceful barb with a deep ruby head on breeding males. Does best in a planted tank with clean water.",
  ["Keep a group of six or more."],aka=["black ruby barb"]),
 A("gold-barb","Gold Barb","Barbodes semifasciolatus","fish","Cyprinidae","Southern China","3 in",(64,75),(6.0,8.0),20,"Active, peaceful","Schooling, keep 6+","Mid","Beginner","Omnivore: flakes, pellets, vegetables","4-6 years",
  "A hardy, golden barb that tolerates cooler water. Good for unheated or lightly heated community tanks.",
  ["Keep a group of six or more."],aka=["golden barb","dwarf golden barb","green barb"]),
 A("denison-barb","Denison Barb","Sahyadria denisonii","fish","Cyprinidae","Western Ghats, India","4.5 in",(65,77),(6.5,7.8),55,"Active, peaceful","Schooling, keep 6+","Mid to upper","Intermediate","Omnivore: flakes, pellets, frozen foods","5-8 years",
  "A fast, bright torpedo-shaped barb that likes a long tank with a current and plenty of oxygen.",
  ["Give it a long tank and good flow.","Keep a group of six or more."],aka=["roseline shark","denison barb","torpedo barb","roseline"]),
 A("tinfoil-barb","Tinfoil Barb","Barbonymus schwanenfeldii","fish","Cyprinidae","Southeast Asia","12 in",(72,77),(6.0,7.5),125,"Active, peaceful but large","Schooling, keep 4+","Mid to upper","Intermediate","Omnivore: pellets, vegetables, frozen foods","8-10 years",
  "A large, fast, silver schooling fish that outgrows most home tanks. It needs a very large aquarium and strong filtration.",
  ["Plan for a large tank (125 gallons or more).","Eats soft plants.","Do not keep with small fish."],aka=["tinfoil barbs","platinum tinfoil barb"]),
 A("melon-barb","Melon Barb","Haludaria fasciata","fish","Cyprinidae","India","3 in",(72,80),(6.0,7.5),20,"Active, peaceful","Schooling, keep 6+","Mid","Beginner","Omnivore: flakes, pellets, frozen foods","4-5 years",
  "A peaceful, shoaling barb with a warm red-orange tone. Prefers a planted tank.",
  ["Keep a group of six or more."],aka=["red panda barb"]),
 A("bala-shark","Bala Shark","Balantiocheilos melanopterus","fish","Cyprinidae","Southeast Asia","12 in",(72,82),(6.5,7.5),150,"Peaceful but large","Schooling, keep 3+","Mid to upper","Intermediate","Omnivore: pellets, frozen foods, vegetables","8-10 years",
  "A silver, shark-shaped schooling fish that grows far larger than the juveniles sold in stores. It needs a very large, long tank.",
  ["Plan for 150 gallons or more.","Do not keep with small fish; they will be eaten.","Use a tight lid."],aka=["bala sharks","silver shark"]),
 A("rainbow-shark","Rainbow Shark","Epalzeorhynchos frenatum","fish","Cyprinidae","Thailand","6 in",(72,79),(6.5,7.5),55,"Territorial","Solitary","Bottom","Intermediate","Omnivore: pellets, algae wafers, frozen foods","5-8 years",
  "A black bottom-dweller with red fins that guards its territory, especially against similar fish. Best kept one per tank.",
  ["Keep only one per tank.","Provide caves and hiding spots."],aka=["albino rainbow shark","rainbow sharks"]),
 A("red-tail-black-shark","Red Tail Black Shark","Epalzeorhynchos bicolor","fish","Cyprinidae","Thailand","6 in",(72,79),(6.5,7.5),55,"Territorial","Solitary","Bottom","Intermediate","Omnivore: pellets, algae wafers, frozen foods","5-8 years",
  "A velvet-black fish with a bright red tail. It claims a cave and chases other bottom fish, so it is usually kept alone.",
  ["Keep only one per tank.","Provide caves and decor to break sight lines."],aka=["red tail shark","red-tailed black shark","redtail shark"]),
 A("flying-fox","Flying Fox","Epalzeorhynchos kalopterus","fish","Cyprinidae","Southeast Asia","6 in",(73,79),(6.0,7.5),55,"Semi-aggressive with its own kind","Solitary","Bottom to mid","Intermediate","Omnivore: algae, pellets, frozen foods","8-10 years",
  "An algae-eating fish with a black stripe and gold body. It can be feisty with its own kind and grows larger than many expect.",
  ["Do not confuse with true Siamese algae eaters.","Keep one per tank."],aka=["red flying fox algae eater","silver flying fox","flying fox algae eater"]),
 A("chinese-algae-eater","Chinese Algae Eater","Gyrinocheilus aymonieri","fish","Gyrinocheilidae","Southeast Asia","10 in",(72,82),(6.5,7.5),55,"Becomes aggressive with age","Solitary","Bottom","Intermediate","Omnivore: algae, algae wafers, vegetables","8-10 years",
  "Often sold as an algae eater, but it grows large and tends to become aggressive. Adults can also suck onto other fish.",
  ["Not a good choice for community tanks as it ages.","Keep only one."],aka=["golden chinese algae eater","chinese algae eaters"]),
 A("medaka","Medaka (Ricefish)","Oryzias latipes","fish","Adrianichthyidae","Japan","1.5 in",(60,82),(6.5,8.0),5,"Peaceful","Small groups, 6+","Upper","Beginner","Micro pellets, flakes","3-4 years",
  "A tiny, hardy rice fish that does well in cool, unheated tanks. Many color varieties exist, all with the same care.",
  ["Tolerates cool water.","Floating plants help with spawning."],aka=["ricefish","rice fish","medaka rice fish","javanese rice fish","indian rice fish"]),
 # ---- Livebearers ----
 A("limia","Limia","Poecilia species","fish","Poeciliidae","Caribbean","2.5 in",(72,80),(7.0,8.5),20,"Peaceful","Small groups","Mid","Beginner","Omnivore: flakes, vegetable foods","3-4 years",
  "Livebearers related to mollies and guppies that like hard, alkaline water with plenty of plant matter in their diet.",
  ["Prefers harder water.","Offer vegetable-based foods."],aka=["perugias limia","tiburon limia","limia tridens","perugia's limia"]),
 # ---- Corydoras / catfish ----
 A("julii-cory","Julii Cory","Corydoras trilineatus","fish","Callichthyidae","Amazon basin, Peru and Brazil","2.5 in",(72,79),(6.0,7.5),20,"Peaceful","Schooling, keep 4+","Bottom","Beginner","Sinking pellets, wafers, frozen foods","5-8 years",
  "A spotted corydoras with a sweet nature. Keep in a group on soft sand or smooth gravel.",
  ["Keep a group of four or more.","Use smooth substrate to protect barbels.","Often sold as julii or three-line cory."],aka=["julii corydoras","corydoras julii","three line cory","julii cory cat"]),
 A("sterbai-cory","Sterbai Cory","Corydoras sterbai","fish","Callichthyidae","Rio Guapore basin, Brazil","2.5 in",(74,82),(6.0,7.5),20,"Peaceful","Schooling, keep 4+","Bottom","Beginner","Sinking pellets, wafers, frozen foods","5-8 years",
  "A striking dotted cory with orange pectoral fins that tolerates warmer water than most corys. Good with discus and other warm-water fish.",
  ["Keep a group of four or more.","Smooth sand protects its barbels."],aka=["sterbai corydoras","sterbai cory cat","albino sterbai cory cat"]),
 A("pygmy-cory","Pygmy Cory","Corydoras pygmaeus","fish","Callichthyidae","Madeira basin, Brazil","1 in",(72,79),(6.0,7.5),10,"Peaceful","Schooling, keep 6+","Bottom to mid","Beginner","Micro pellets, crushed wafers, frozen foods","3-5 years",
  "A tiny corydoras that swims mid-water as well as along the bottom. Great for nano tanks in a group.",
  ["Keep a group of six or more.","Feed tiny foods."],aka=["pygmy cory cat","pygmy corydoras","dwarf cory","tail spot pygmy cory cat","venezuelan pygmy cory","habrosus cory cat","habrosus cory"]),
 A("skunk-cory","Skunk Cory","Corydoras arcuatus","fish","Callichthyidae","Amazon basin, Peru and Brazil","2.25 in",(72,79),(6.0,7.5),20,"Peaceful","Schooling, keep 4+","Bottom","Beginner","Sinking pellets, wafers, frozen foods","5-8 years",
  "A small cory marked with a dark stripe from nose to tail. Easy and active in a group.",
  ["Keep a group of four or more."],aka=["skunk cory cat","skunk corydoras"]),
 A("albino-cory","Albino Cory","Corydoras aeneus (albino variety)","fish","Callichthyidae","Captive-bred","2.75 in",(72,79),(6.0,7.8),20,"Peaceful","Schooling, keep 4+","Bottom","Beginner","Sinking pellets, wafers, frozen foods","5-8 years",
  "A pale, pink-eyed form of the bronze cory. Same easy care; keep it in a group on smooth substrate.",
  ["Keep a group of four or more.","Albino fish may dislike very bright light."],aka=["albino corydoras","albino cory cat","gold laser cory cat","gold green cory cat","green gold cory cat","gold-green corydorus"]),
 A("corydoras-assorted","Assorted Corydoras","Corydoras species","fish","Callichthyidae","South America","2-3 in",(72,79),(6.0,7.5),20,"Peaceful","Schooling, keep 4+","Bottom","Beginner","Sinking pellets, wafers, frozen foods","5-8 years",
  "Most corydoras share the same care: a group of four or more, smooth sand or gravel, and clean, stable water.",
  ["Keep a group of four or more of one species.","Use smooth substrate.","Check the exact species for size and temperature."],aka=["assorted corydoras","cory cat","corydoras","assorted cory cat","bandit cory cat","elegans corydoras","agassizii cory cat","paleatus corydoras","peppered corydoras","c115 cory cat","punctatus cory cat","loxozonus cory cat","kanei cory cat","emerald green cory cat","rust cory cat","orange venezuelan cory cat","black venezuelan cory cat","venezuelan red sailfin cory cat","blue corydoras","gold panda cory cat","long fin panda corydora","delphax cory cat","false blochi cat","smudge spot cory cat"]),
 A("common-pleco","Common Pleco","Hypostomus plecostomus","fish","Loricariidae","Northern South America","15 in",(72,82),(6.5,7.5),125,"Peaceful but large","Solitary","Bottom","Intermediate","Omnivore: algae wafers, vegetables, driftwood","10-15 years",
  "Common plecos are sold small but grow to a foot or more and produce a lot of waste. Only get one if you can provide a large tank.",
  ["Plan for a big tank (125 gallons or more).","Offer driftwood and vegetables.","It is not a cleanup crew."],aka=["common plecos","albino common pleco","orange spotted common pleco","orange spotted pleco","mama pleco","plecostomus"]),
 A("golden-nugget-pleco","Golden Nugget Pleco","Baryancistrus xanthellus","fish","Loricariidae","Xingu River, Brazil","7 in",(78,86),(6.0,7.5),55,"Peaceful, territorial around caves","Solitary or small groups","Bottom","Intermediate","Omnivore: wafers, vegetables, frozen foods","10-15 years",
  "A striking spotted pleco from the Xingu. Needs warm, well-oxygenated, clean water with caves and flow.",
  ["Needs warm, oxygen-rich water.","Provide caves; do not overcrowd."],aka=["l018 golden nugget pleco","l177 gold seam golden nugget pleco","golden nugget plecos","l081 golden nugget pleco","gold seam golden nugget pleco"]),
 A("clown-pleco","Clown Pleco","Panaqolus maccus","fish","Loricariidae","Orinoco basin, Venezuela","4 in",(73,82),(6.0,7.5),20,"Peaceful","Solitary or pairs","Bottom","Beginner","Wood-eater: driftwood, wafers, vegetables","10-12 years",
  "A small, striped pleco that rasps on driftwood as part of its diet, so always provide wood. A good small-tank choice.",
  ["Keep driftwood in the tank at all times.","Provide a cave."],aka=["clown pleco l104","l104 clown pleco","clown plecos","l-104"]),
 A("zebra-pleco","Zebra Pleco","Hypancistrus zebra","fish","Loricariidae","Xingu River, Brazil","3.5 in",(80,86),(6.0,7.5),20,"Peaceful","Small groups","Bottom","Advanced","Carnivore leaning omnivore: frozen foods, sinking pellets","8-10 years",
  "A bold black-and-white pleco that needs warm, very clean, well-oxygenated water and caves. Prized and best for experienced keepers.",
  ["Needs warm, clean, high-oxygen water.","Feed meaty frozen foods.","Provide small caves."],aka=["l46 zebra pleco","l046 zebra pleco","hypancistrus zebra","l-46"]),
 A("royal-pleco","Royal Pleco","Panaque nigrolineatus","fish","Loricariidae","Orinoco and Amazon basins","16 in",(75,82),(6.0,7.5),125,"Territorial","Solitary","Bottom","Intermediate","Wood-eater: driftwood, vegetables, wafers","15-20 years",
  "A large, handsome pleco that needs a lot of driftwood and a very large tank when grown.",
  ["Provide plenty of driftwood.","Plan for a large tank."],aka=["royal pleco l191","l191 royal pleco","panaque nigrolineatus"]),
 A("whiptail-catfish","Whiptail Catfish","Rineloricaria and Farlowella species","fish","Loricariidae","South America","5-7 in",(72,80),(6.0,7.5),30,"Peaceful, shy","Solitary or small groups","Bottom","Intermediate","Algae, blanched vegetables, sinking foods","5-8 years",
  "Slim, twig-like catfish that graze on algae and soft biofilm. Need clean, well-oxygenated water and gentle tankmates.",
  ["Add only to mature tanks with biofilm.","Needs high-quality water."],aka=["whiptail pleco","farlowella catfish","royal farlowella catfish","twig catfish","red lizard whiptail catfish"]),
 A("hoplo-catfish","Hoplo Catfish","Megalechis thoracata","fish","Callichthyidae","South America","7 in",(68,82),(6.0,8.0),40,"Peaceful","Solitary or groups","Bottom","Beginner","Omnivore: pellets, frozen foods, worms","10-15 years",
  "A hardy armored catfish that scavenges on the bottom and can eat very small fish.",
  ["Provide caves.","Do not keep with tiny fish."],aka=["hoplo","port hoplo"]),
 A("synodontis-catfish","Synodontis Catfish","Synodontis species","fish","Mochokidae","Africa","4-10 in",(73,82),(7.0,8.5),55,"Peaceful to semi-aggressive","Varies by species","Bottom","Intermediate","Omnivore: pellets, frozen foods, vegetables","8-15 years",
  "A large group of African catfish that includes upside-down catfish, featherfin and petricola types. Size and temperament vary, so check the exact species.",
  ["Provide caves.","Size varies a lot by species."],aka=["upside down catfish","upside-down catfish synodontis","moustache synodontis catfish","featherfin squeaker","dwarf petricola synodontis catfish","synodontis eupterus","synodontis valentiana","synodontis piedratus","petricola"]),
 A("pictus-catfish","Pictus Catfish","Pimelodus pictus","fish","Pimelodidae","Amazon basin, South America","5 in",(72,80),(6.0,7.5),55,"Peaceful but eats small fish","Small groups","Bottom to mid","Intermediate","Carnivore leaning omnivore: pellets, frozen foods","8-10 years",
  "An active, spotted catfish with long barbels. It will eat small tankmates and needs a long tank.",
  ["Do not keep with tiny fish.","Needs swimming room."],aka=["pictus cat","four line pictus catfish"]),
 A("raphael-catfish","Raphael Catfish","Platydoras armatulus","fish","Doradidae","South America","6 in",(72,80),(6.0,7.5),40,"Peaceful, nocturnal","Solitary","Bottom","Beginner","Omnivore: pellets, frozen foods","15+ years",
  "A talking catfish that hides during the day and makes a squeaking sound. Provide hiding spots.",
  ["Provide caves and hiding places.","Will eat very small fish."],aka=["striped raphael catfish","spotted raphael catfish","talking catfish"]),
 A("banjo-catfish","Banjo Catfish","Bunocephalus species","fish","Aspredinidae","South America","4 in",(72,80),(6.0,7.5),20,"Peaceful, nocturnal","Solitary","Bottom","Intermediate","Sinking foods, frozen worms","8-10 years",
  "A flat, leaf-like catfish that buries itself in sand. Needs a soft sandy bottom and gentle tankmates.",
  ["Use soft sand.","Feed after lights out."],aka=["banjo cat"]),
 # ---- Loaches ----
 A("yoyo-loach","Yoyo Loach","Botia almorhae","fish","Botiidae","India and Pakistan","6 in",(73,80),(6.5,7.5),40,"Active, semi-aggressive","Small groups","Bottom","Intermediate","Omnivore: pellets, frozen foods, snails","10-15 years",
  "An active, playful loach with a pattern that resembles the letters of its name when young. Best in a group.",
  ["Keep a group of three or more.","Provide caves."],aka=["yoyo loaches","golden yoyo loach","botia almorhae"]),
 A("dojo-loach","Dojo Loach","Misgurnus anguillicaudatus","fish","Cobitidae","East Asia","10 in",(60,75),(6.0,8.0),55,"Peaceful","Small groups","Bottom","Beginner","Omnivore: sinking pellets, frozen foods, worms","10-15 years",
  "A hardy, eel-like loach that tolerates cooler water. Needs soft sand and a tight lid because it can escape.",
  ["Use soft sand.","Use a tight lid.","Reacts to pressure changes."],aka=["weather loach","dojo loaches","golden dojo loach","albino dojo loach"]),
 A("zebra-loach","Zebra Loach","Botia striata","fish","Botiidae","Western Ghats, India","4 in",(73,80),(6.5,7.5),30,"Active, semi-peaceful","Small groups","Bottom","Intermediate","Omnivore: sinking foods, frozen foods","8-10 years",
  "A small, striped loach that is active and social. Keep with a group and provide caves.",
  ["Keep three or more.","Provide caves."],aka=["zebra loaches"]),
 A("hillstream-loach","Hillstream Loach","Sewellia lineolata and related species","fish","Balitoridae","Southeast Asia","2.5 in",(65,75),(6.5,7.8),20,"Peaceful","Small groups","Bottom","Advanced","Algae and biofilm, small frozen foods","5 years",
  "A flat, fast-water loach that grazes on algae and biofilm. Needs cool, highly oxygenated, flowing water.",
  ["Needs cool, oxygen-rich, flowing water.","Add to a mature tank with biofilm."],aka=["reticulated hillstream loach","butterfly hillstream loach","alligator hillstream loach","gecko loach","chinese hillstream loach","hong kong otocinclus","panda garra","garra flavatra","hong kong plec"]),
 A("botia-loach","Botia Loach","Botia species","fish","Botiidae","Southeast Asia","4-8 in",(73,82),(6.0,7.5),40,"Active, may nip","Small groups","Bottom","Intermediate","Omnivore: sinking foods, frozen foods","8-15 years",
  "Botia loaches are active, social bottom fish. Several species are sold; check the exact one for adult size.",
  ["Keep in groups.","Provide caves."],aka=["redtail botia loach","splendida botia loach","tiger botia loach","serpent loach botia","skunk loach","botia","tiger botia"]),
 A("dwarf-chain-loach","Dwarf Chain Loach","Ambastaia sidthimunki","fish","Botiidae","Thailand and Myanmar","2 in",(75,82),(6.0,7.5),20,"Active, peaceful","Groups of 6+","Bottom to mid","Intermediate","Omnivore: small sinking foods, frozen foods","8 years",
  "A tiny, busy loach that does best in a group. Needs stable, clean water and caves.",
  ["Keep six or more.","Feed small foods."],aka=["dwarf chain loaches","pygmy loach"]),
 A("horseface-loach","Horseface Loach","Acantopsis choirorhynchos","fish","Cobitidae","Southeast Asia","8 in",(72,82),(6.0,7.5),40,"Peaceful","Solitary or groups","Bottom","Intermediate","Sinking foods, worms","10 years",
  "A sand-sifting loach that buries itself and sifts the substrate. Needs soft sand.",
  ["Needs fine soft sand.","Gentle tankmates only."],aka=["horse face loach"]),
 # ---- Gouramis, bettas, labyrinths ----
 A("giant-gourami","Giant Gourami","Osphronemus goramy","fish","Osphronemidae","Southeast Asia","24 in",(72,82),(6.0,8.0),300,"Large, may be aggressive","Solitary","Mid","Advanced","Omnivore: pellets, vegetables, frozen foods","15+ years",
  "Small giant gouramis are sold young, but they grow to two feet and need a pond-size aquarium.",
  ["Only for very large tanks.","Plan for decades of care."],aka=["albino true giant gourami","true giant gourami","leucistic giant gourami","red tail giant gourami","giant red tail gourami"]),
 A("opaline-gourami","Opaline Gourami","Trichopodus trichopterus","fish","Osphronemidae","Southeast Asia","6 in",(72,82),(6.0,8.0),30,"Peaceful, can be territorial","Solitary or pairs","Upper to mid","Beginner","Omnivore: flakes, pellets, frozen foods","4-6 years",
  "A hardy, larger gourami with a marbled pattern. Males can become territorial with each other.",
  ["Keep one male per tank.","Provide floating plants."],aka=["three spot gourami","gold gourami","opaline","cosby gourami","gold gourami"]),
 A("flame-gourami","Flame Gourami","Trichogaster lalius","fish","Osphronemidae","South Asia","3 in",(72,82),(6.0,7.5),20,"Peaceful, males can squabble","Solitary or pairs","Upper","Beginner","Omnivore: flakes, pellets, frozen foods","4 years",
  "The red-orange form of the dwarf gourami group. Peaceful and easy in a planted community tank.",
  ["Provide floating plants.","Keep one male per tank."],aka=["dwarf flame gourami","neon dwarf gourami","flame dwarf gourami","female dwarf gourami","dwarf gourami assorted"]),
 A("licorice-gourami","Licorice Gourami","Parosphromenus species","fish","Osphronemidae","Southeast Asia","1.5 in",(72,80),(4.0,6.0),10,"Peaceful, shy","Pairs","Mid","Advanced","Tiny live and frozen foods","3 years",
  "A tiny, delicate blackwater gourami that needs soft, acidic water and live foods. For experienced keepers.",
  ["Needs soft, acidic water.","Feed tiny live or frozen foods."],aka=["moonspot licorice gourami","licorice gouramis","sparkling gourami","pygmy gourami","croaking gourami","chocolate gourami","samurai gourami","thicklip sunset gourami"]),
 A("paradise-fish","Paradise Fish","Macropodus opercularis","fish","Osphronemidae","East Asia","4 in",(60,78),(6.0,8.0),20,"Aggressive","Solitary or pairs","Upper","Intermediate","Omnivore: flakes, pellets, frozen foods","6-8 years",
  "A hardy, colorful labyrinth fish that tolerates cool water but is aggressive toward its own kind and small tankmates.",
  ["Keep one male per tank.","Use a lid with a gap for air."],aka=["paradise fish macropodus opercularis"]),
 A("plakat-betta","Plakat Betta","Betta splendens (short-finned)","fish","Osphronemidae","Captive-bred, Southeast Asia origin","2.5 in",(76,82),(6.0,7.5),5,"Aggressive toward other bettas","Solitary","Upper","Beginner","Carnivore leaning omnivore: betta pellets, frozen foods","3-5 years",
  "Plakat bettas are short-finned varieties, active and hardy. Keep males singly, and pair only with calm tankmates.",
  ["One male per tank.","Heated, filtered tanks only."],aka=["plakat bettas","giant plakat betta","dragon plakat betta","platinum plakat betta","koi plakat betta","dumbo plakat betta","plakat betta short tail betta","malay thai plakat betta","male koi plakat betta","wild type plakat betta"]),
 # ---- Cichlids ----
 A("severum","Severum","Heros severus","fish","Cichlidae","Amazon basin, South America","8 in",(76,82),(6.0,7.5),75,"Semi-aggressive, usually calm","Solitary or pairs","Mid","Intermediate","Omnivore: pellets, vegetables, frozen foods","10-15 years",
  "A large, deep-bodied cichlid that is generally calmer than other big cichlids. Does best in a roomy tank with steady water changes.",
  ["Needs a large tank.","Offer vegetables as part of the diet."],aka=["red spotted severum","gold severum","green severum","red shoulder severum","red tiger severum","golden severum","severums"]),
 A("peacock-bass","Peacock Bass","Cichla species","fish","Cichlidae","South America","20 in",(76,84),(6.0,7.5),300,"Predatory","Solitary","Mid to upper","Advanced","Carnivore: whole foods, frozen fish, shrimp","10-15 years",
  "A fast, predatory cichlid that grows large and needs a very large tank and strong filtration. Not for casual keepers.",
  ["Needs a very large tank.","Eats fish."],aka=["temensis peacock bass","orinoco peacock bass","kelberi peacock bass","azul peacock bass","mono peacock bass","xingu peacock bass","cichla","peacock bass fry"]),
 A("geophagus","Geophagus","Geophagus species","fish","Cichlidae","South America","8 in",(75,82),(5.5,7.5),75,"Peaceful to semi-aggressive","Small groups","Mid to bottom","Intermediate","Omnivore: sinking pellets, frozen foods","8-10 years",
  "Sand-sifting eartheaters that sift through the substrate. Need fine sand and open space.",
  ["Use fine sand.","Do regular water changes."],aka=["jurupari geophagus","geophagus brasiliensis","eartheater","jurupari"]),
 A("blood-parrot-cichlid","Blood Parrot Cichlid","Hybrid cichlid","fish","Cichlidae","Captive-bred hybrid","8 in",(76,82),(6.5,7.5),55,"Semi-aggressive","Solitary or pairs","Mid","Beginner","Omnivore: pellets, frozen foods","10-15 years",
  "A captive-bred hybrid with a rounded head and small mouth. Hardy but can be territorial.",
  ["Needs a roomy tank.","Dye-enhanced fish may lose color."],aka=["blood parrot","king kong parrot","king kong parrot xl","kkp","yuan bao blood parrot","blue tiger parrot","parrot cichlid"]),
 A("firemouth-cichlid","Firemouth Cichlid","Thorichthys meeki","fish","Cichlidae","Central America","6 in",(72,82),(6.5,8.0),40,"Semi-aggressive","Pairs","Mid to bottom","Intermediate","Omnivore: pellets, frozen foods","8-10 years",
  "A hardy Central American cichlid that flares its red throat when threatened.",
  ["Needs a roomy tank.","Provide caves."],aka=["firemouth"]),
 A("tropheus","Tropheus","Tropheus species","fish","Cichlidae","Lake Tanganyika, Africa","5 in",(74,80),(7.8,9.0),75,"Territorial","Large groups","Mid","Advanced","Algae and vegetable foods; avoid high protein","8-10 years",
  "A rock-dwelling cichlid from Lake Tanganyika that lives in large groups. It needs hard, alkaline water and a vegetable-based diet.",
  ["Needs hard, alkaline water.","Use a plant-based diet; high protein can cause bloat."],aka=["tropheus moliro firecracker","tropheus moliro"]),
 A("multies-shell-dweller","Multifasciatus Shell Dweller","Lamprologus multifasciatus","fish","Cichlidae","Lake Tanganyika, Africa","2 in",(74,80),(7.5,9.0),10,"Territorial in a colony","Colony","Bottom","Intermediate","Small frozen and live foods, micro pellets","5-8 years",
  "A tiny cichlid that lives and breeds in empty snail shells. Great for a colony tank with a sand bottom.",
  ["Use sand and plenty of empty shells.","Needs hard, alkaline water."],aka=["multies","shell dweller","multifasciatus"]),
 A("uaru","Uaru","Uaru amphiacanthoides","fish","Cichlidae","Amazon basin, South America","10 in",(78,84),(5.5,7.0),125,"Peaceful but large","Pairs or groups","Mid","Advanced","Omnivore: vegetables, pellets, frozen foods","10+ years",
  "A shy, large, disc-shaped cichlid that needs soft, clean water and a roomy tank.",
  ["Needs soft, very clean water.","Keep calm tankmates."],aka=["panda uaru","triangle cichlid","uaru amphiacanthoides"]),
 A("german-gold-ram","German Gold Ram","Mikrogeophagus ramirezi (gold variety)","fish","Cichlidae","Captive-bred","2.5 in",(78,85),(5.5,7.0),20,"Peaceful","Pairs","Bottom to mid","Intermediate","Omnivore: micro pellets, frozen foods","2-4 years",
  "A golden form of the ram cichlid. Needs warm, clean water and stable conditions.",
  ["Keep warm and stable.","Feed small foods."],aka=["gold ram","german gold rams"]),
 A("apistogramma","Apistogramma","Apistogramma species","fish","Cichlidae","South America","3 in",(74,82),(5.0,7.0),20,"Peaceful, territorial around caves","Harem or pair","Bottom to mid","Intermediate","Carnivore leaning omnivore: frozen foods, micro pellets","3-5 years",
  "Dwarf cichlids with big personalities. Males are larger and more colorful. Provide caves and plants.",
  ["Provide caves.","Keep one male with several females."],aka=["apistogramma macmasteri","apistogramma panduro","apisto macmasteri","apisto","dwarf agassizii","agassizii apisto","apistogramma agassizii","apistogramma sp steel blue","blue neon apisto"]),
 A("electric-blue-jack-dempsey","Electric Blue Jack Dempsey","Rocio octofasciata (blue variety)","fish","Cichlidae","Captive-bred","10 in",(75,82),(6.5,8.0),75,"Aggressive","Solitary or pair","Mid","Intermediate","Carnivore leaning omnivore: pellets, frozen foods","10-15 years",
  "A vivid blue cultivated form of the Jack Dempsey. Territorial and not suited to small or peaceful tankmates.",
  ["Needs a large tank.","Keep with similarly sized fish."],aka=["ebjd","electric blue jd","electric blue jack dempsey ebjd"]),
 A("green-spotted-puffer","Green Spotted Puffer","Dichotomyctere nigroviridis","fish","Tetraodontidae","Southeast Asia","6 in",(75,82),(7.5,8.5),30,"Aggressive","Solitary","Mid to bottom","Advanced","Carnivore: snails, shrimp, crustaceans","10 years",
  "A bold, intelligent puffer that grows up in brackish water. It needs hard-shelled foods to keep its teeth worn down and eats most tankmates.",
  ["Brackish water long term.","Feed snails and shelled foods.","Keep alone."],aka=["gsp","xl green spotted puffer gsp","green spotted puffer gsp","green spotted puffers"]),
 A("fahaka-puffer","Fahaka Puffer","Tetraodon lineatus","fish","Tetraodontidae","Nile and Congo basins, Africa","16 in",(72,82),(7.0,8.0),180,"Aggressive","Solitary","Mid to bottom","Advanced","Carnivore: snails, shrimp, crustaceans","10+ years",
  "A large, aggressive freshwater puffer that needs a very large tank and a diet of hard-shelled foods.",
  ["Keep alone.","Feed hard-shelled foods for its teeth.","Needs a very large tank."],aka=["fahaka","fahaka puffer small","nile puffer"]),
 A("mbu-puffer","Mbu Puffer","Tetraodon mbu","fish","Tetraodontidae","Congo basin, Africa","26 in",(75,82),(7.0,8.0),500,"Aggressive","Solitary","Mid to bottom","Advanced","Carnivore: snails, shrimp, crustaceans","10+ years",
  "The largest freshwater puffer, needing an enormous tank. For specialists only.",
  ["Needs a very large tank.","Keep alone."],aka=["tetraodon mbu puffer","mbu"]),
 A("dwarf-puffer-specialty","Specialty Puffers","Various species","fish","Tetraodontidae","Africa, South America, Southeast Asia","varies",(72,82),(6.5,8.0),30,"Often aggressive","Species-dependent","Mid to bottom","Advanced","Carnivore: snails, shrimp, crustaceans","8-12 years",
  "Pufferfish vary a lot in size and temperament, but most eat hard-shelled foods and nip fins. Check the exact species before buying.",
  ["Research each species.","Feed hard-shelled foods.","Most should be kept alone."],aka=["amazon puffer","freshwater amazon puffer","congo puffer","avocado puffer","red eye somphongs puffer","red spotted puffer","pao abei puffer","humpback dragon puffer","twin spot target puffer","orange saddle fugu puffer","spotted congo puffer","tetraodon miurus"]),
 A("bichir","Bichir","Polypterus species","fish","Polypteridae","Africa","12-30 in",(72,82),(6.0,8.0),75,"Predatory, peaceful with large fish","Solitary or groups","Bottom","Intermediate","Carnivore: pellets, frozen foods","15-20 years",
  "Ancient-looking, long-lived fish that can breathe air. Many species grow to a foot or more. Use a tight lid because they escape.",
  ["Use a tight lid.","Do not keep with small fish."],aka=["senegal bichir","ornate bichir","delhezi bichir","endlicheri bichir","lapradei bichir","palmas bichir","guinean bichir","albino cuvier bichir","mokele mbembe bichir","gray bichir","bichirs","cuvier bichir"]),
 A("knifefish","Knifefish","Chitala, Notopterus and related species","fish","Notopteridae","Africa and Asia","10-36 in",(75,82),(6.0,7.5),75,"Predatory, shy","Solitary","Mid to bottom","Intermediate","Carnivore: frozen foods, pellets","10-15 years",
  "Long, flattened fish that hunt at night. Many grow large and eat small tankmates.",
  ["Provide hiding spots.","Do not keep with small fish."],aka=["clown knifefish","albino clown knifefish","royal clown knifefish","black ghost knifefish","african brown knifefish","ghost knifefish","clown knife"]),
 A("elephant-nose-fish","Elephantnose Fish","Gnathonemus petersii","fish","Mormyridae","Africa","9 in",(73,82),(6.0,7.5),55,"Peaceful, shy","Solitary or small groups","Bottom to mid","Advanced","Carnivore: live and frozen blackworms, bloodworms","10 years",
  "A fascinating, nocturnal electric fish that senses its world through an electric field. Needs soft sand, hiding spots, and calm tankmates.",
  ["Use soft sand.","Offer worms; it is often a picky eater."],aka=["elephantnose","elephant nose fish","elephant nose","blunt jawed elephantnose fish"]),
 A("silver-dollar","Silver Dollar","Metynnis species","fish","Serrasalmidae","South America","6 in",(72,82),(6.0,7.5),55,"Peaceful, skittish","Schooling, keep 5+","Mid","Beginner","Herbivore leaning omnivore: vegetables, pellets, flakes","10 years",
  "A disc-shaped schooling fish that eats plants and needs a roomy, long tank.",
  ["Keep a group of five or more.","Offer vegetables; it eats soft plants."],aka=["silver dollar fish","red hook silver dollar fish","blue hook silver dollar fish","spotted silver dollar fish"]),
 A("red-belly-pacu","Red Belly Pacu","Piaractus brachypomus","fish","Serrasalmidae","Amazon basin, South America","24 in",(72,82),(6.0,7.5),400,"Large, skittish","Solitary","Mid","Advanced","Omnivore: vegetables, fruit, pellets","15+ years",
  "Pacu are sold small but grow to two feet or more and need a very large tank.",
  ["Not suitable for most homes.","Needs a huge tank."],aka=["pacu","red belly pacu","red-bellied pacu"]),
 A("datnoid","Datnoid","Datnioides species","fish","Datnioididae","Southeast Asia","18 in",(75,82),(6.5,7.5),180,"Predatory","Solitary","Mid","Advanced","Carnivore: frozen fish, shrimp, live foods","10-15 years",
  "A striking striped predator that needs a large tank and meaty foods.",
  ["Do not keep with small fish.","Needs a large tank."],aka=["tiger datnoid","indo tiger datnoid","thin bar datnoid","ngt datnoid","siamese tiger fish","indonesian tiger datnoid"]),
 A("gar","Gar","Lepisosteidae and related species","fish","Lepisosteidae","Americas","20-48 in",(65,82),(6.5,8.0),300,"Predatory","Solitary","Upper","Advanced","Carnivore: whole fish","10-20 years",
  "Long, ambush predators that need very large tanks and secure lids. Specialist fish.",
  ["Needs a very large tank.","Use a heavy lid."],aka=["needle nose gar","spotted pike characin false gar","hujeta gar","xl hujeta gar","freshwater barracuda","red tail barracuda","yellow tail barracuda"]),
 A("arowana-other","Black Arowana and Other Arowana","Osteoglossum and Scleropages species","fish","Osteoglossidae","South America, Asia, Australia","24-36 in",(76,84),(6.0,7.5),300,"Predatory","Solitary","Upper","Advanced","Carnivore: insects, fish, shrimp","15-20 years",
  "Arowana grow very large and need huge, long tanks with secure lids. Several species are sold; check legal and care requirements.",
  ["Needs a very large tank and tight lid.","Check species and legal requirements."],aka=["black arowana","blue arowana","jardini arowana","leichardti arowana","saratoga","african arowana","arowana fry","arapaima","arapaima gigas","paiche","pirarucu"]),
 A("koi","Koi","Cyprinus carpio","fish","Cyprinidae","Captive-bred","24 in",(40,80),(7.0,8.5),500,"Peaceful","Groups","All levels","Intermediate","Omnivore: koi pellets, vegetables","25+ years",
  "Koi are pond fish that grow very large. Small koi can live in aquariums only temporarily.",
  ["Plan for a pond.","Cannot stay in small tanks."],aka=["koi fish","gold koi fish","black koi fish","butterfly koi fish","malayan butterfly koi","panda koi fish","tri color koi","koi fish assorted bundle of three"]),
 # ---- Killifish, rainbowfish, misc ----
 A("killifish","Killifish","Aphyosemion, Aplocheilus and related species","fish","Aplocheilidae","Africa, Asia, Americas","2-4 in",(70,78),(6.0,7.5),10,"Peaceful to semi-aggressive","Pairs or trios","Upper","Intermediate","Small live and frozen foods, micro pellets","1-5 years",
  "Often brightly colored, jump-prone fish that sit near the surface. Many are short-lived. Use a tight lid.",
  ["Use a tight lid.","Offer live or frozen foods."],aka=["lamp eye killifish","clown killifish","golden wonder killifish","gardneri killifish","blue lyretail killifish","indian lamp eye killifish","normans lampeye killifish","iridescent toothcarp","american flag fish","blue lyretail"]),
 A("rainbowfish","Rainbowfish","Melanotaenia and related species","fish","Melanotaeniidae","Australia and New Guinea","4 in",(72,80),(7.0,8.0),30,"Peaceful, active","Schooling, keep 6+","Upper to mid","Beginner","Omnivore: flakes, pellets, frozen foods","5-8 years",
  "Active, colorful schooling fish that need long tanks and hard, alkaline water.",
  ["Keep a group of six or more.","Give it room to swim.","Prefers harder water."],aka=["turquoise rainbowfish","celebes rainbowfish","madagascar rainbowfish","red irian rainbowfish","blue eye forktail rainbowfish","featherfin rainbowfish","threadfin rainbow","paska red neon rainbow","paskai rainbowfish","pacific signifier blue eye rainbowfish","gertrudes spotted blue eye rainbowfish","red neon blue eye rainbowfish","rainbow shiner"]),
 A("pencilfish","Pencilfish","Nannostomus species","fish","Lebiasinidae","South America","2 in",(72,82),(5.5,7.0),10,"Peaceful, shy","Schooling, keep 6+","Upper to mid","Intermediate","Micro pellets, frozen foods, baby brine shrimp","3-5 years",
  "Slender, shy fish with a bold stripe, best in a planted tank with dim light.",
  ["Keep a group of six or more.","Use a tight lid."],aka=["pencil fish","pencil fish nannostomus","beckfords red pencil fish","beckfords golden pencil fish"]),
 A("assassin-snail","Assassin Snail","Anentome helena","invert","Nassariidae","Southeast Asia","1 in",(72,82),(7.0,8.0),5,"Predatory toward snails","Groups","Bottom","Beginner","Carnivore: snails, frozen foods","2-3 years",
  "A striped snail that hunts other snails. Useful against pest snails, but it will also eat ramshorns and mystery snails.",
  ["Do not keep with snails you want to keep.","Feed meaty foods if snails run out."],aka=["assassin snails"]),
 A("ramshorn-snail","Ramshorn Snail","Planorbidae","invert","Planorbidae","Worldwide","0.5 in",(65,82),(6.5,8.0),5,"Peaceful","Colony","All levels","Beginner","Algae, detritus, vegetables","1-2 years",
  "Flat, coil-shelled snails that reproduce quickly and eat algae and leftover food.",
  ["Population follows food supply.","Safe with most plants."],aka=["blue ramshorn snail","red ramshorn snail","giant ramshorn snail","ramshorn snails"]),
 A("trapdoor-snail","Trapdoor Snail","Viviparus species","invert","Viviparidae","Asia","1.5 in",(65,78),(7.0,8.0),10,"Peaceful","Groups","Bottom","Beginner","Algae, detritus","2-3 years",
  "A live-bearing snail with a sealable operculum. Prefers cooler water.",
  ["Prefers cool to moderate temperatures.","Does not eat plants."],aka=["japanese trapdoor snail","striped wizard trapdoor snail","white wizard trapdoor snail"]),
 A("rabbit-snail","Rabbit Snail","Tylomelania species","invert","Pachychilidae","Sulawesi, Indonesia","3 in",(76,84),(7.5,8.5),10,"Peaceful","Groups","Bottom","Beginner","Algae, detritus, sinking foods, vegetables","3 years",
  "A large, cone-shaped Sulawesi snail that produces only a few young at a time. Likes warm, hard, alkaline water.",
  ["Needs warm, hard water.","Safe with plants."],aka=["assorted rabbit snail","chocolate rabbit snail","golden rabbit snail","orange volcano rabbit snail","white spotted towuti rabbit snail","sulawesi snail"]),
 A("inca-snail","Inca Snail","Doryssa species","invert","Thiaridae","South America","1 in",(72,80),(7.0,8.5),5,"Peaceful","Groups","Bottom","Beginner","Algae, detritus, sinking foods","3 years",
  "A hardy snail that burrows in sand and grazes.",
  ["Safe with plants.","Burrows in sand."],aka=["gold inca snail","blueberry snail","conehead snail","algae king koopa snail","prambanan snail","malaysian trumpet snail"]),
 A("bamboo-shrimp","Bamboo Shrimp","Atyopsis moluccensis","invert","Atyidae","Southeast Asia","3 in",(72,82),(6.5,7.5),20,"Peaceful","Solitary","Mid","Intermediate","Filter feeder: powdered foods, fine particles","2 years",
  "A filter-feeding shrimp that fans its arms in the current. Needs a mature tank with fine food particles.",
  ["Use a gentle flow.","Feed powdered foods."],aka=["baby bamboo shrimp","jumbo bamboo shrimp","vampire shrimp","atya gabonensis"]),
 A("caridina-shrimp","Caridina Shrimp","Caridina species","invert","Atyidae","Asia","1 in",(68,76),(5.5,7.0),5,"Peaceful","Colony","All levels","Intermediate","Algae, biofilm, shrimp foods","1-2 years",
  "Crystal, bee and tiger shrimp often need softer, more stable water than neocaridina. Use RO water remineralized for shrimp.",
  ["Use stable, soft water.","Avoid copper and sudden changes."],aka=["crystal red shrimp","super red crystal shrimp","pure red line","taiwan bee","tiger shrimp","tangerine tiger shrimp","orange eye blue tiger shrimp","super tiger shrimp","blue bolt shrimp","panda shrimp","shadow panda shrimp","red panda shrimp","black king kong shrimp","red king kong shrimp","snowball shrimp","blue velvet shrimp","golden back yellow shrimp","bloody mary shrimp","galaxy shrimp","fishbone shrimp","caridina","blue dream shrimp","ultra blue shrimp"]),
 A("neocaridina-color-shrimp","Neocaridina Color Shrimp","Neocaridina davidi","invert","Atyidae","Taiwan (captive-bred)","1 in",(65,82),(6.5,8.0),5,"Peaceful","Colony","All levels","Beginner","Algae, biofilm, shrimp foods","1-2 years",
  "Easy shrimp in many colors: yellow, blue, green, black, orange, and rili patterns. Same care as cherry shrimp.",
  ["Keep a group.","Avoid copper."],aka=["rili shrimp","blue rili shrimp","green rili shrimp","carbon rili shrimp","orange rili shrimp","black rili shrimp","red rili shrimp","yellow cherry shrimp","blue dream shrimp","sunkist shrimp","green jade shrimp","blueberry shrimp","orange eye fire red neocaridina","fire red shrimp","snow ball shrimp","blue sapphire shrimp","green sapphire shrimp","ultra gold shrimp","black diamond shrimp","black rose shrimp"]),
 A("crayfish","Dwarf and Specialty Crayfish","Cambarellus and Cherax species","invert","Cambaridae","Americas, Australia","1.5-6 in",(65,78),(7.0,8.0),10,"Territorial, will eat tankmates","Solitary or species group","Bottom","Intermediate","Omnivore: sinking pellets, vegetables, frozen foods","2-4 years",
  "Crayfish are escape artists and will eat small fish and shrimp. Dwarf Mexican crayfish stay smaller and are gentler.",
  ["Use a tight lid.","Provide hiding spots.","Do not keep with shrimp or small fish."],aka=["mexican dwarf crayfish","orange cpo mexican dwarf crayfish","blue lobster","electric blue lobster","snow white lobster","tangerine lobster","orange tip lobster","bluemoon lobster","common crayfish","asian tiger lobster","zebra lobster","extreme red holdout lobster","blue lobster cherax"]),
 A("freshwater-crab","Freshwater Crab","Geosesarma, Cardisoma and related species","invert","Varies","Southeast Asia and elsewhere","1-3 in",(72,82),(6.5,8.0),10,"Escape artist","Species-dependent","Land and water","Intermediate","Omnivore: pellets, vegetables, frozen foods","2-4 years",
  "Vampire, panda, red devil and other crabs are semi-terrestrial. They need land area and a very secure lid.",
  ["Provide land and water.","Use a very secure lid."],aka=["vampire crab","panda crab","red devil crab","red apple crab","thai micro crab","fiddler crab","pom pom crab","mandarin crab","halloween vampire crab","purple vampire crab","red clawed crab","disco vampire crab","thai devil crab","rainbow vampire crabs","panther crab","carnival yellow vampire crab","banana crab","red chili crab"]),
 A("hermit-crab-freshwater","Dwarf Hermit Crab","Clibanarius tricolor","invert","Diogenidae","Caribbean","1 in",(72,80),(8.0,8.4),5,"Peaceful","Groups","Bottom","Intermediate","Algae, detritus, sinking foods","2-5 years",
  "Often sold as freshwater hermit crabs, but these are saltwater animals and cannot live long term in freshwater. We mention it so you can choose accurately.",
  ["Not a true freshwater animal.","Ask staff for suitable freshwater alternatives."],aka=["blue leg dwarf hermit crabs","yellow tip hermit crabs","hermit crab"]),
 A("clam-freshwater","Freshwater Clam","Corbicula and Anodonta species","invert","Corbiculidae","Asia","1-2 in",(65,80),(7.0,8.0),10,"Peaceful","Groups","Bottom","Advanced","Filter feeder: fine particles, algae","1-3 years",
  "Filter-feeding clams are difficult to feed well in home tanks and often starve. Only for experienced keepers.",
  ["Need an established tank with microscopic food.","Often short-lived."],aka=["asian gold clam","mini yellow clam"]),
]

MORE_PLANTS = [
 P("bacopa-caroliniana","Bacopa Caroliniana","Bacopa caroliniana","Plantaginaceae","Southeastern United States","12-20 in","Medium","Optional","Background, stem plant","Moderate",(68,82),(6.0,7.5),"Beginner","Cuttings",
  "A forgiving stem plant with round leaves that turns bronze-pink under strong light.",
  ["Plant stems in groups.","Trim the tops to bush out."],aka=["bacopa","bacopa caroliniana red","bacopa monnieri","bacopa moneri","bacopa monniera","bacopa moneywort","moneywort","bacopa compacta","bacopa amplexicaulis","bacopa araguai","bacopa madagascariensis","bacopa salzmannii","brazilian bacopa"]),
 P("ludwigia-red","Red Ludwigia","Ludwigia species","Onagraceae","Americas","10-20 in","Medium to high","Helpful","Midground to background, stem plant","Moderate to fast",(68,82),(6.0,7.5),"Beginner","Cuttings",
  "A red-leaved stem plant that shows its best color under strong light and with iron-rich fertilizer.",
  ["Strong light brings out red.","Trim tops and replant."],aka=["ludwigia palustris","ludwigia inclinata","ludwigia glandulosa","ludwigia peruensis","super red ludwigia","ludwigia natans super red","ludwigia sedioides","ludwigia ovalis","ludwigia crystal","ludwigia arcuata","ludwigia senegalensis","ludwigia broad leaf","red ludwigia","mini super red ludwigia","white edge ludwigia","ludwigia dark orange","ludwigia pantanal","ludwigia peruensis gladulosa var diamond","ludwigia repens dark"]),
 P("alternanthera-reineckii","Alternanthera Reineckii","Alternanthera reineckii","Amaranthaceae","South America","8-16 in","Medium to high","Helpful","Midground to background, stem plant","Moderate",(68,82),(6.0,7.5),"Intermediate","Cuttings",
  "A reddish-purple stem plant, popular in colorful aquascapes. Needs good light and nutrients.",
  ["Use strong light for color.","Replant trimmed tops."],aka=["alternanthera","alternanthera rosaefolia","alternanthera rosanervig","alternanthera lilacina","alternanthera bettzickiana","alternanthera mini","alternanthera reineckii mini","alternanthera reineckii bronze","alternanthera reineckii rosaefolia","alternanthera amabilis tricolor","alternanthera cardinalis","alternanthera variegatus","alternanthera reineckii mini kerala","alternanthera reineckii red broad leaf","alternanthera rosifolia","bettzickiana","scarlet temple bunch"]),
 P("hygrophila","Hygrophila","Hygrophila species","Acanthaceae","Asia","10-24 in","Low to medium","Optional","Background, stem plant","Fast",(68,86),(6.0,7.8),"Beginner","Cuttings",
  "Fast-growing, hardy stem plants that help absorb excess nutrients. Several species are sold, including lancea and difformis.",
  ["Trim often to keep it dense.","Easy for beginners."],aka=["hygrophila lancea","hygrophila lancea araguaia","hygrophila siamensis","hygrophila difformis","water wisteria hygrophila","hygrophila rubra","hygrophila angustifolia","hygrophila pogonocalyx","hygrophila lacustris","hygrophila corymbosa","nomaphila","nomaphila stricta","nomaphila siamensis","nomaphila variegatus","giant hygro"]),
 P("staurogyne-repens","Staurogyne Repens","Staurogyne repens","Acanthaceae","South America","3 in","Medium","Optional","Foreground to midground, carpeting stem","Moderate",(70,82),(6.0,7.5),"Beginner","Cuttings",
  "A low, bushy plant that forms a lush carpet and is easier than many foreground plants.",
  ["Trim to keep it low.","Moderate light is enough."],aka=["staurogyne","staurogyne bihar","staurogyne porto velho","staurogyne sp bihar","staurogyne sp porto velho"]),
 P("pogostemon-helferi","Pogostemon Helferi (Downoi)","Pogostemon helferi","Lamiaceae","Thailand","2 in","Medium to high","Helpful","Foreground, rosette","Slow to moderate",(70,82),(6.0,7.5),"Intermediate","Runners and division",
  "A crinkled, low rosette plant that forms a carpet. Sensitive to rough planting and low nutrients.",
  ["Plant gently.","Keep it well fed with root tabs."],aka=["downoi","pogostemon helferi downoi","pogostemon erectus","pogostemon stellatus","pogostemon stellata octopus","pogostemon octopus"]),
 P("dwarf-baby-tears","Dwarf Baby Tears (HC Cuba)","Hemianthus callitrichoides","Linderniaceae","Cuba","1-2 in","High","Required","Foreground, carpeting","Moderate",(68,78),(6.0,7.5),"Advanced","Division",
  "A tiny-leaved, lush carpet plant that needs strong light and CO2 to stay low and dense.",
  ["Needs strong light and CO2.","Plant in small portions."],aka=["hc cuba","hemianthus callitrichoides","cuba dwarf baby tears","dwarf baby tears hemianthus callitrichoides","hemianthus cuba"]),
 P("micro-sword","Micro Sword","Lilaeopsis brasiliensis","Apiaceae","South America","2-3 in","Medium to high","Helpful","Foreground, carpeting","Moderate",(68,82),(6.0,7.5),"Intermediate","Runners",
  "A grass-like carpet plant that spreads by runners when it gets light and nutrients.",
  ["Plant in small clumps.","Needs strong light for a tight carpet."],aka=["lilaeopsis","lilaeopsis brasiliensis","lilaeopsis novaezelandiae","lilaeopsis mauritiana","micro sword lilaeopsis novaezelandiae","brazilian micro sword"]),
 P("hornwort","Hornwort","Ceratophyllum demersum","Ceratophyllaceae","Worldwide","24+ in","Low to medium","Optional","Floating or anchored, stem","Fast",(60,86),(6.0,8.0),"Beginner","Cuttings",
  "A fast-growing, rootless plant that absorbs nutrients and shelters fry. It can shed needles when stressed.",
  ["Float it or loosely anchor it.","Trim often."],aka=["horntwort","horntwort bunch","hornwort bunch","coontail"]),
 P("water-lettuce","Water Lettuce","Pistia stratiotes","Araceae","Tropics worldwide","4 in above water","Medium to high","Not needed","Floating","Fast",(68,86),(6.0,7.5),"Beginner","Daughter plants",
  "A floating rosette with long roots that gives shade and cover. Keep the leaves dry and give it strong light.",
  ["Keep leaves dry.","Needs strong light."],aka=["water lettuce pista stratiotes","pistia"]),
 P("salvinia","Salvinia","Salvinia species","Salviniaceae","Tropics worldwide","1 in","Medium to high","Not needed","Floating","Fast",(65,86),(6.0,7.5),"Beginner","Division",
  "A tiny floating fern that spreads rapidly and shades the tank. Keep the leaves dry and thin it as needed.",
  ["Keep leaves dry.","Thin regularly."],aka=["salvinia natans","salvinia cucullata","floating fern","salvinia natans floating fern","azolla","azolla fairy moss","fairy moss","azolla filiculoides","water mimosa","sensitive plant floater"]),
 P("red-root-floater","Red Root Floater","Phyllanthus fluitans","Phyllanthaceae","South America","2 in above water","High","Not needed","Floating","Moderate",(72,84),(5.5,7.5),"Intermediate","Division",
  "A floating plant whose roots and leaves turn red under bright light and with nutrient-rich water.",
  ["Needs strong light for red color.","Keep leaves dry."],aka=["red root floaters","phyllanthus fluitans"]),
 P("christmas-moss","Christmas Moss","Vesicularia montagnei","Hypnaceae","Southeast Asia","2-4 in","Low to medium","Not needed","Attach to wood or rock, carpet","Slow",(68,82),(6.0,7.5),"Beginner","Division",
  "A moss with a fir-tree look that makes a lush carpet or wall. Needs gentle trimming and clean water.",
  ["Tie it to wood or rock.","Keep it clean of debris."],aka=["christmas moss 1 pound","mini christmas moss","floating christmas moss ball","christmas moss wreath","heart shaped christmas moss wreath","spiky moss","spikey moss","taiwan moss","taxiphyllum alternans","taxiphyllum barberi","taxiphyllum spiky","taxiphyllum giant","peacock moss","pellia","flame moss","fissidens","fissidens fontanus","subwassertang","cameroon moss","bendable moss vine","riccia","riccia fluitans","pearl moss","plagiomnium","erect moss"]),
 P("marimo-moss-ball","Marimo Moss Ball","Aegagropila linnaei","Cladophoraceae","Northern lakes","1-3 in","Low","Not needed","Anywhere, loose","Very slow",(55,78),(6.5,8.0),"Beginner","Division",
  "A slow-growing green algae ball that is easy to keep. Roll it occasionally and keep it out of direct sun and hot water.",
  ["Roll it now and then.","Keep it cool."],aka=["marimo","moss ball","marimo moss"]),
 P("java-fern-varieties","Java Fern Varieties","Microsorum pteropus","Polypodiaceae","Southeast Asia","6-14 in","Low to medium","Not needed","Attach to wood or rock","Slow",(68,82),(6.0,7.5),"Beginner","Rhizome division",
  "Java fern varieties such as narrow leaf, trident, windelov and lace share the same care as regular java fern. Attach them to hardscape and do not bury the rhizome.",
  ["Do not bury the rhizome.","Use thread or glue to attach."],aka=["java fern narrow leaf","java fern windelov","windelov java fern","java fern trident","trident fern","java fern lettuce","java fern flaming","java fern sunrise","java fern xl","giant java fern","microsorum pteropus coral","microsorum pteropus fish tail","microsorum windelov twisted","narrow leaf java fern","microsorum pteropus java","microsorum pteropus narrow leaf","microsorum pteropus malaysian red","java fern broad leaf"]),
 P("bolbitis","Bolbitis","Bolbitis heudelotii","Dryopteridaceae","Africa and Asia","6-14 in","Low to medium","Not needed","Attach to wood or rock","Slow",(68,82),(6.0,7.5),"Intermediate","Rhizome division",
  "A slow, graceful fern that attaches to hardscape. Does best in stable, mature tanks.",
  ["Do not bury the rhizome.","Be patient; it grows slowly."],aka=["bolbitis heudelotii","asian water fern","bolbitis heteroclita","mini bolbitis","african water fern","bolbitis difformis","borneo fern"]),
 P("cryptocoryne-parva","Cryptocoryne Parva","Cryptocoryne parva","Araceae","Sri Lanka","2-4 in","Low to medium","Not needed","Foreground, carpeting rosette","Slow",(72,82),(6.0,7.5),"Beginner","Runners",
  "A tiny crypt that carpets slowly. May melt after planting and regrow.",
  ["Expect melt after planting.","Do not move it once settled."],aka=["crypt parva","cryptocoryne parva tissue culture","crypt pygmaea","cryptocoryne pygmaea","cryptocoryne lucens","cryptocoryne lutea","cryptocoryne undulata","cryptocoryne balansae","cryptocoryne spiralis","cryptocoryne retrospiralis","cryptocoryne crispatula","cryptocoryne becketii","cryptocoryne walkeri","cryptocoryne petchii","cryptocoryne nurii","cryptocoryne usteriana","cryptocoryne willisii","cryptocoryne albida","cryptocoryne costata","cryptocoryne axelrodi","cryptocoryne hudoroi","cryptocoryne mioya","cryptocoryne tropica","crypt sri lanka","crypt blassii","cryptocoryne thwaitesii","cryptocoryne wendtii bronze","cryptocoryne wendtii brown","cryptocoryne wendtii green gecko","cryptocoryne wendtii red","cryptocoryne wendtii sindoor","cryptocoryne wendtii tropica","cryptocoryne wendtii green","cryptocoryne wendtii bronze crypt"]),
 P("anubias-varieties","Anubias Varieties","Anubias species","Araceae","West Africa","3-16 in","Low to medium","Not needed","Attach to wood or rock","Slow",(68,86),(6.0,7.5),"Beginner","Rhizome division",
  "Anubias are very hardy, slow plants. Barteri, coffeefolia, petite, hastifolia, congensis, gigantea and others share the same care. Do not bury the rhizome.",
  ["Do not bury the rhizome.","Keep leaves clear of algae with low-medium light."],aka=["anubias","anubias barteri","anubias coffeefolia","anubias petite","anubias nana petite","anubias hastifolia","anubias congensis","anubias gigantea","anubias afzelii","anubias frazeri","anubias glabra","anubias heterophylla","anubias lanceolata","anubias stardust","anubias nangi","anubias minima","anubias nana golden","anubias nana white","anubias nana variegated","anubias snow white","anubias white","anubias marble","anubias butterfly","anubias jungle star","anubias emerald bloom","anubias chili jalapeno","anubias on cocofiber","anubias mini coin","anubias short and sharp","anubias barteri round leaf","anubias nana thick leaf","anubias nana long wavy","anubias nana paxing compact","anubias white rose","anubias golden coin","xl anubias","anubias nana mother pot","anubias afzelii african broadleaf"]),
 P("echinodorus-varieties","Echinodorus Varieties","Echinodorus species","Alismataceae","Americas","8-24 in","Medium","Not needed","Midground to background, rosette","Moderate",(68,82),(6.0,7.5),"Beginner","Runners and plantlets",
  "A large family of rosette plants including amazon sword, bleherae, ozelot, rose, red flame, marble queen and radican swords. All like rich substrate and root tabs.",
  ["Feed with root tabs.","Trim old leaves."],aka=["echinodorus","sword plant","echinodorus bleheri","echinodorus ozelot","echinodorus rose","echinodorus aflame","echinodorus red flame","echinodorus marble queen","echinodorus reni","echinodorus cordifolius","echinodorus osiris","echinodorus jaguar","echinodorus harbich","echinodorus hadi","echinodorus horizontalis","echinodorus parviflorus","echinodorus big bear","kleiner prinz sword","argentine sword plant","rosette sword plant","red mellon sword plant","amazon sword plant","echinodorus tenellus","helanthium tenellum","helanthium vesuvius","pygmy chain sword"]),
 P("vallisneria-varieties","Vallisneria Varieties","Vallisneria species","Hydrocharitaceae","Worldwide","6-40 in","Low to medium","Not needed","Background, grass-like","Fast",(65,86),(6.5,8.0),"Beginner","Runners",
  "Easy, grass-like plants including corkscrew, jungle, giant and nana forms. Spread by runners to form a lush background.",
  ["Keep crowns above the substrate.","Trim leaves as needed."],aka=["vallisneria spiralis","vallisneria nana","vallisneria asiatica","vallisneria gigantea","vallisneria torta","corkscrew vallisneria","corkscrew val","jungle val","giant val","jungle val vallisneria americana","vallisneria gigantea rubra"]),
 P("aponogeton","Aponogeton","Aponogeton species","Aponogetonaceae","Africa, Asia, Madagascar","8-20 in","Medium","Not needed","Midground to background, bulb","Moderate",(68,82),(6.0,7.5),"Intermediate","Bulb division",
  "Bulb plants with big, graceful leaves. They may go dormant and then regrow; do not discard the bulb.",
  ["Do not bury the bulb fully.","Expect rest periods."],aka=["aponogeton natans","aponogeton madagascar lace bulb","madagascar lace","betta bulbs","betta bulbs aponogeton sp","lace plant"]),
 P("marsilea","Marsilea","Marsilea species","Marsileaceae","Worldwide","1-3 in","Medium to high","Helpful","Foreground, carpet","Moderate",(68,82),(6.0,7.5),"Intermediate","Runners",
  "A clover-leaf carpet plant that spreads in strong light.",
  ["Needs strong light and nutrients.","Plant in small clumps."],aka=["marsilea hirsuta","marsilea crenata","marsilea angustifolia","dwarf four-leaf clover","four leaf clover plant"]),
 P("hydrocotyle","Hydrocotyle (Pennywort)","Hydrocotyle species","Araliaceae","Worldwide","2-10 in","Medium","Not needed","Carpet, midground, floating","Fast",(65,82),(6.0,7.5),"Beginner","Cuttings",
  "Hardy pennywort species that create floating, carpeting or tall bush forms depending on type.",
  ["Trim often.","Gives cover for fry."],aka=["hydrocotyle verticillata","hydrocotyle tripartita","hydrocotyle sibthorpioides","hydrocotyle leucocephala","hydrocotyle japan","brazilian pennywort","marsh pennywort","lawn marsh pennywort","dwarf pennywort"]),
 P("rotala-varieties","Rotala Varieties","Rotala species","Lythraceae","Asia","6-16 in","Medium to high","Helpful","Midground to background, stem plant","Moderate to fast",(68,82),(5.5,7.5),"Intermediate","Cuttings",
  "Colorful stem plants such as hra, macrandra, blood red, florida sunset and vietnam. Reward strong light and nutrients.",
  ["Strong light brings out red and pink.","Trim and replant tops."],aka=["rotala hra","rotala macrandra","rotala blood red","rotala florida sunset","rotala vietnam","rotala vietnam hra","rotala bossii","rotala ceylon","rotala indica","rotala mexicana","rotala colorata","rotala narrow leaf red","rotala coin leaf","rotala sp goias","rotala sp myanmar","rotala manipurensis","rotala fujian","rotala orange juice","rotala red","rotala bonsai","rotala wallichii","rotala macrandra mini","rotala macrandra shimoga","premium rotala"]),
 P("ammannia","Ammannia","Ammannia species","Lythraceae","Africa and Asia","6-14 in","Medium to high","Helpful","Midground to background, stem plant","Moderate",(70,82),(6.0,7.5),"Intermediate","Cuttings",
  "Colorful red stem plants such as bonsai, gracilis and sulawesi. Like strong light and steady nutrients.",
  ["Needs strong light.","Trim and replant."],aka=["ammania","ammania bonsai","ammania gracilis","ammannia gracilis","ammannia senegalensis","ammannia sp sulawesi","ammania sp sulawesi","ammannia sp nesaea crassicaulis","nesaea","nesaea triflora","nesaea pedicellata","nesaea crassicaulis"]),
 P("eleocharis","Eleocharis (Hairgrass)","Eleocharis species","Cyperaceae","Worldwide","2-8 in","Medium to high","Helpful","Foreground, carpet","Moderate",(65,82),(6.0,7.5),"Intermediate","Runners",
  "Fine grass-like carpet plants. Need good light and nutrients to spread.",
  ["Plant in small clumps.","Trim to keep it neat."],aka=["eleocharis acicularis","eleocharis parvula","eleocharis vivipara","eleocharis acicularis mini","hairgrass eleocharis parvula","eleocharis pusillis","eleocharis"]),
 P("najas-guppy-grass","Guppy Grass","Najas guadalupensis","Hydrocharitaceae","Americas","12-24 in","Low to medium","Not needed","Floating or anchored, stem","Fast",(65,86),(6.0,8.0),"Beginner","Cuttings",
  "A delicate, fast-growing plant that hides fry and absorbs nutrients.",
  ["Trim often.","Great for fry cover."],aka=["najas","najas guadalupensis","guppy grass","guppy grass najas"]),
 P("parrots-feather","Parrot's Feather","Myriophyllum aquaticum","Haloragaceae","South America","12+ in","Medium to high","Optional","Background, stem plant","Fast",(60,82),(6.0,8.0),"Beginner","Cuttings",
  "A feathery plant that grows above water as well as below. Use caution in outdoor ponds because it can be invasive.",
  ["Never release it outdoors.","Trim often."],aka=["myriophyllum aquaticum","myriophyllum guyana","myriophyllum","foxtail","watermilfoil"]),
 P("limnophila","Limnophila","Limnophila species","Plantaginaceae","Asia","8-16 in","Medium","Optional","Background, stem plant","Fast",(68,82),(6.0,7.5),"Beginner","Cuttings",
  "Feathery, fast-growing stem plants such as sessiliflora and heterophylla that absorb nutrients quickly.",
  ["Trim often.","Good for new tanks."],aka=["limnophila sessiliflora","limnophila heterophylla","limnophila vietnam mini","limnophila belem","ambulia"]),
 P("mayaca","Mayaca","Mayaca fluviatilis","Mayacaceae","Americas","6-12 in","Medium to high","Helpful","Background, stem plant","Moderate",(68,82),(6.0,7.0),"Intermediate","Cuttings",
  "A fine-leaved moss-like stem plant that likes soft water and strong light.",
  ["Needs strong light.","Trim and replant."],aka=["mayaca fluviatilis"]),
 P("lotus-tiger","Tiger Lotus","Nymphaea species","Nymphaeaceae","Tropical regions","8-20 in","Medium to high","Optional","Midground to background, bulb","Fast",(68,86),(6.0,7.5),"Beginner","Bulb division",
  "A bulb plant with big, speckled leaves that can reach the surface. Trim floating leaves to let light through.",
  ["Trim surface leaves.","Plant the bulb half-buried."],aka=["green tiger lotus","red tiger lotus","tiger lotus","nymphea stellata","dwarf lily","banana plant","nymphoides aquatica","banana plant nymphoides aquatica"]),
 P("pothos-emersed","Pothos and Houseplants for Tanks","Epipremnum and related species","Araceae","Tropics","varies","Low to high","Not needed","Roots in water, leaves out of water","Fast",(65,86),(6.0,8.0),"Beginner","Cuttings",
  "Pothos, philodendron and other houseplants can grow roots in aquarium water to absorb nutrients. Only the roots go in the water; the leaves stay in the air.",
  ["Keep leaves above water.","Great for nitrate control."],aka=["epipremnum aureum","epipremnun aureum","philodendron cordatum","syngonium podophyllum","lucky bamboo","tradescantia zebrine","boston fern","water adapted boston fern","nephrolepis exaltata","fittonia","fittonia albivenis","begonia arabian sunset","far east man plant pot holder","ardisia dino","dendobium orchid","african onion plant","selaginella","ophiopogon","ophiopogon pusillus","kyoto ophiopogon japonicus","hemigraphis","hemigraphis exotica","hemigraphis repanda"]),
 P("bucephalandra-varieties","Bucephalandra Varieties","Bucephalandra species","Araceae","Borneo","2-6 in","Low to medium","Not needed","Attach to wood or rock","Slow",(68,82),(6.0,7.5),"Intermediate","Rhizome division",
  "Slow, compact epiphytes with beautiful leaf colors and many named varieties, such as brownie, kedagang, godzilla and theia. Do not bury the rhizome.",
  ["Do not bury the rhizome.","Stable water matters."],aka=["bucephalandra brownie","bucephalandra kedagang","bucephalandra godzilla","bucephalandra theia","bucephalandra velvet","bucephalandra pygmy","bucephalandra lamandau","bucephalandra sekadau","bucephalandra biblis","bucephalandra flamingo","bucephalandra marble","bucephalandra apple leaf","bucephalandra wavy green","bucephalandra red mini","bucephalandra grappa","bucephalandra pandora","arrogant blue bucephalandra","black pearl bucephalandra","titan bucephalandra","homalomena","homalomena sekadau","homalomena silver","homalomena humilis","homalomena insignis","piptospatha","piptospatha ridleyi","lagenandra","lagenandra meeboldii","lagenandra bleeding heart","barclaya","barclaya longifolia"]),
 P("anacharis-egeria","Anacharis","Egeria densa","Hydrocharitaceae","South America","12-24 in","Medium","Optional","Background, stem or floating","Fast",(60,82),(6.0,8.0),"Beginner","Cuttings",
  "A fast, hardy stem plant that absorbs nutrients. Use caution outdoors; it can be invasive.",
  ["Never release it outdoors.","Trim often."],aka=["egeria densa","anacharis egeria densa","elodea","brazilian waterweed"]),
 P("amazon-frogbit-floaters","Frogbit and Floaters","Limnobium and similar species","Hydrocharitaceae","Americas","2 in above water","Medium to high","Not needed","Floating","Fast",(68,86),(6.0,7.5),"Beginner","Division",
  "Floating plants that shade the tank and soak up nutrients. Keep leaves dry and thin them regularly.",
  ["Thin regularly.","Keep leaves dry."],aka=["amazon frogbit floater plant","mosaic bareroof floater plant","hygroryza aristata","floating bamboo","rorippa aquatica","penthorum sedoides","ranalisma rostratum"]),
 P("tissue-culture-plant","Tissue Culture Plants","Various","Various","Various","varies","Varies","Varies","Varies","Varies",(68,82),(6.0,7.5),"Beginner","Varies",
  "Tissue culture plants are grown in sterile cups, so they come free of snails and pests. Rinse off the gel, divide into small plantlets, and plant them. Care follows the plant type.",
  ["Rinse off all gel.","Divide into small portions and plant."],aka=["tissue culture","uns tissue culture","tissue culture bundle"]),
]

# Alias merges into batch-1 entries (variants Pet Zone lists that belong to an existing guide)
ALIAS_INTO = {
 "discus": ["pigeon blood discus","snakeskin discus","blue snakeskin discus","blue diamond discus","fuji apple discus","wild discus","white diamond discus","red melon discus","melon red discus","leopard spotted discus","marlboro red discus","checkerboard pigeon discus","albino discus","assorted discus","yellow pigeon discus","lemon yellow discus","sunshine discus","rose red discus","blue turquoise discus","discus breeding pair","albino pigeon blood discus","yellow melon discus","red turquoise discus"],
 "oscar": ["tiger oscar","super red tiger oscar","albino tiger oscar","red oscar","albino oscar"],
 "flowerhorn": ["thai silk flowerhorn","kamfa flowerhorn","srd flowerhorn","zz flowerhorn","diamond blue flowerhorn","flowerhorn fry","short body flowerhorn","flowerhorn mirror","dwarf srt flowerhorn","cz flowerhorn"],
 "fancy-goldfish": ["oranda goldfish","ranchu goldfish","ryukin goldfish","pearlscale goldfish","black moor goldfish","bubble eye goldfish","panda oranda","butterfly tail goldfish","telescope goldfish","calico ranchu goldfish","red cap oranda goldfish","lionhead goldfish"],
 "guppy": ["dumbo guppy","blue dumbo guppy","albino red guppy","red guppy","platinum guppy","tuxedo guppy","koi guppy","mosaic guppy","lyretail guppy","cobra guppy","moscow guppy","black moscow guppy","santa claus dumbo guppy","red dragon guppy","tiger guppy","female guppy","male guppy","gold dumbo guppy","guppy assorted","jumbo male guppy","jumbo female guppy","red cap guppy","black metal lace guppy","panda guppy"],
 "endlers-livebearer": ["tiger endler guppy","female endlers livebearer guppy","endlers livebearer guppy","cobra green endlers guppy"],
 "platy": ["sunset platy","mickey mouse platy","redwag platy","hi fin platy","asst platy","variatus platy"],
 "swordtail": ["hi fin red velvet swordtail","hi fin red swordtail","solar flare twinbar swordtail","kohaku swordtail","koi swordtail","mickey mouse swordtail","velvet red swordtail","swordtail guppy","swordtail assorted"],
 "molly": ["sailfin molly","balloon molly","lyretail balloon molly","golden panda lyretail molly","gold dust molly","dalmatian molly"],
 "angelfish": ["koi angelfish","marble angelfish","blue angelfish","black angelfish"],
 "kuhli-loach": ["black kuhli loach","neon kuhli loach","striped kuhli loach","jumbo striped kuhli loach"],
 "clown-loach": ["clown loach 2 inches","clown loach 2-3 inches"],
 "bristlenose-pleco": ["super red bristlenose pleco","super red bristle nose pleco","albino bristlenose pleco","albino longfin bristlenose pleco","long fin bristlenose","bushy nose pleco","bushynose pleco","gold bushynose albino pleco","blue eye lemon pleco","lemon pleco","l144a","l149 black cucuta pleco","ancistrus"],
 "otocinclus": ["zebra otocinclus","otocinclus affinis","otocinclus catfish","otocinclus cocama","otocinclus marinae"],
 "neon-tetra": ["jumbo neon tetra","gold neon tetra","golden neon tetra","platinum neon tetra","diamond head neon tetra"],
 "celestial-pearl-danio": ["galaxy rasbora","galaxy rasbora celestial pearl danio"],
 "harlequin-rasbora": ["purple harlequin rasbora","green kubotai rasbora","kubotai rasbora"],
 "tiger-barb": ["green tiger barb","golden tiger barb","albino tiger barb","platinum green tiger barb","albino blushing tiger barb","xl golden tiger barb","large tiger barb"],
 "cherry-barb": ["long fin cherry barb","albino cherry barb"],
 "congo-tetra": ["long fin congo tetra","albino congo tetra"],
 "rummy-nose-tetra": ["golden rummynose tetra","asian rummynose","sawbwa resplendens"],
 "silver-arowana": ["albino silver arowana","leucistic silver arowana","albino silver arowana small","albino silver arowana xl","albino silver arowana small 1","silver arowana fry","silver arowana small","silver arowana medium","silver arowana large","silver arowana xl","wild caught silver arowana"],
 "pea-puffer": ["malabar dwarf puffer","pea puffer jumbo size","dwarf puffer"],
 "german-blue-ram": ["long fin german blue ram","blue ram","electric blue ram","electric blue balloon ram","balloon ram","dwarf blue ram","gold ram blue"],
 "honey-gourami": ["sunset honey gourami","red honey gourami","golden honey gourami","dwarf honey gourami"],
 "betta": ["halfmoon betta","crowntail betta","veiltail betta","dumbo betta","koi betta","dragon scale betta","delta tail betta","king betta","giant betta","female betta","male betta","betta assorted","black samurai betta","rose tail betta","yellow dragon betta","black orchid betta","hellboy betta","galaxy betta","nemo betta","halfmoon dumbo betta","double tail betta","giant koi betta","juvenile betta"],
 "nerite-snail": ["zebra nerite snail","tiger nerite snail","red racer nerite snail","batman nerite snail","olive nerite snail","batik nerite snail","horned nerite snail","tricolor horned nerite snail"],
 "mystery-snail": ["blue mystery snail","ivory mystery snail","albino mystery snail","black mystery snail","yellow mystery snail","gold mystery snail"],
 "amano-shrimp": ["xl amano shrimp","lot of 10 amano shrimp","lot of 5 amano shrimp"],
 "neocaridina-shrimp": ["cherry shrimp","red cherry shrimp","sakura shrimp","rcs"],
 "amazon-sword": ["amazon sword plant"],
 "monte-carlo": ["micranthemum monte carlo"],
 "ludwigia-repens": ["red ludwigia ludwigia repens"],
 "rotala-rotundifolia": ["rotala rotundifolia orange juice","rotala rotundifolia platinum","rotala rotundifolia red"],
 "java-fern": [],
}
